//! Model catalog (AI_MODELS) and capabilities re-export.
//! Ports AI_MODELS from src/shared/constants/models.js (built from open-sse/config/providerModels.js).
//! Caps + get_capabilities_for_model are re-exported from the Phase 3 registry
//! (providers::registry::capabilities), which implements the full 4-step fallback chain.

/// AI_MODELS entry: (provider_alias, model_id, model_name)
/// Ported from Object.entries(PROVIDER_MODELS).flatMap(...) in models.js
pub static AI_MODELS: &[(&str, &str, &str)] = &[
    ("alicode-intl", "qwen3.5-plus", "Qwen3.5 Plus"),
    ("alicode-intl", "kimi-k2.5", "Kimi K2.5"),
    ("alicode-intl", "glm-5", "GLM 5"),
    ("alicode-intl", "MiniMax-M2.5", "MiniMax M2.5"),
    ("alicode-intl", "qwen3-coder-next", "Qwen3 Coder Next"),
    ("alicode-intl", "qwen3-coder-plus", "Qwen3 Coder Plus"),
    ("alicode-intl", "glm-4.7", "GLM 4.7"),
    ("alicode", "qwen3.5-plus", "Qwen3.5 Plus"),
    ("alicode", "kimi-k2.5", "Kimi K2.5"),
    ("alicode", "glm-5", "GLM 5"),
    ("alicode", "MiniMax-M2.5", "MiniMax M2.5"),
    ("alicode", "qwen3-max-2026-01-23", "Qwen3 Max"),
    ("alicode", "qwen3-coder-next", "Qwen3 Coder Next"),
    ("alicode", "qwen3-coder-plus", "Qwen3 Coder Plus"),
    ("alicode", "glm-4.7", "GLM 4.7"),
    ("anthropic", "claude-sonnet-4-20250514", "Claude Sonnet 4"),
    ("anthropic", "claude-opus-4-20250514", "Claude Opus 4"),
    ("anthropic", "claude-3-5-sonnet-20241022", "Claude 3.5 Sonnet"),
    ("ag", "gemini-3.8-flash-high", "Gemini 3.8 Flash (High)"),
    ("ag", "gemini-3.8-flash-medium", "Gemini 3.8 Flash (Medium)"),
    ("ag", "gemini-3.8-flash-low", "Gemini 3.8 Flash (Low)"),
    ("ag", "gemini-3.8-flash", "Gemini 3.8 Flash"),
    ("ag", "gemini-3.7-flash-high", "Gemini 3.7 Flash (High)"),
    ("ag", "gemini-3.7-flash-medium", "Gemini 3.7 Flash (Medium)"),
    ("ag", "gemini-3.7-flash-low", "Gemini 3.7 Flash (Low)"),
    ("ag", "gemini-3.6-flash-high", "Gemini 3.6 Flash (High)"),
    ("ag", "gemini-3.6-flash-medium", "Gemini 3.6 Flash (Medium)"),
    ("ag", "gemini-3.6-flash-low", "Gemini 3.6 Flash (Low)"),
    ("ag", "gemini-3.5-flash-high", "Gemini 3.5 Flash (High)"),
    ("ag", "gemini-3-flash-agent", "Gemini 3.5 Flash (High)"),
    ("ag", "gemini-3.5-flash-low", "Gemini 3.5 Flash (Medium)"),
    ("ag", "gemini-3.5-flash-extra-low", "Gemini 3.5 Flash (Low)"),
    ("ag", "gemini-pro-agent", "Gemini 3.1 Pro (High)"),
    ("ag", "gemini-3.1-pro-low", "Gemini 3.1 Pro (Low)"),
    ("ag", "claude-sonnet-4-6", "Claude Sonnet 4.6 (Thinking)"),
    ("ag", "claude-opus-4-6-thinking", "Claude Opus 4.6 (Thinking)"),
    ("ag", "gpt-oss-120b-medium", "GPT-OSS 120B (Medium)"),
    ("ag", "gemini-3-flash", "Gemini 3 Flash"),
    ("ag", "gemini-3.1-flash-image", "Gemini 3.1 Flash (Image)"),
    ("assemblyai", "universal-3-pro", "Universal 3 Pro"),
    ("assemblyai", "universal-2", "Universal 2"),
    ("assemblyai", "best", "Best (Nano + Universal)"),
    ("assemblyai", "nano", "Nano (Fast)"),
    ("black-forest-labs", "flux-pro-1.1", "FLUX Pro 1.1"),
    ("black-forest-labs", "flux-pro-1.1-ultra", "FLUX Pro 1.1 Ultra"),
    ("black-forest-labs", "flux-pro", "FLUX Pro"),
    ("black-forest-labs", "flux-dev", "FLUX Dev"),
    ("black-forest-labs", "flux-kontext-pro", "FLUX Kontext Pro (Edit)"),
    ("black-forest-labs", "flux-kontext-max", "FLUX Kontext Max (Edit)"),
    ("blackbox", "claude-fable-5", "Claude Fable 5"),
    ("blackbox", "claude-opus-4.8", "Claude Opus 4.8"),
    ("blackbox", "claude-sonnet-4.6", "Claude Sonnet 4.6"),
    ("blackbox", "gpt-5.5", "GPT-5.5"),
    ("blackbox", "gpt-5.4-pro", "GPT-5.4 Pro"),
    ("blackbox", "gpt-5.4", "GPT-5.4"),
    ("blackbox", "gpt-5.3-codex", "GPT-5.3 Codex"),
    ("blackbox", "gpt-5.4-nano", "GPT-5.4 Nano"),
    ("blackbox", "deepseek-v4-flash", "DeepSeek V4 Flash"),
    ("blackbox", "grok-4.3", "Grok 4.3"),
    ("byteplus", "seed-2-0-pro-260328", "Seed 2.0 Pro"),
    ("byteplus", "seed-2-0-code-preview-260328", "Seed 2.0 Code Preview"),
    ("byteplus", "seed-2-0-mini-260215", "Seed 2.0 Mini"),
    ("byteplus", "seed-2-0-lite-260228", "Seed 2.0 Lite"),
    ("byteplus", "kimi-k2-thinking-251104", "Kimi K2 Thinking"),
    ("byteplus", "glm-4-7-251222", "GLM 4.7"),
    ("byteplus", "gpt-oss-120b-250805", "GPT-OSS-120B"),
    ("cerebras", "gpt-oss-120b", "GPT OSS 120B"),
    ("cerebras", "zai-glm-4.7", "ZAI GLM 4.7"),
    ("cerebras", "llama-3.3-70b", "Llama 3.3 70B"),
    ("cerebras", "llama-4-scout-17b-16e-instruct", "Llama 4 Scout"),
    ("cerebras", "qwen-3-235b-a22b-instruct-2507", "Qwen3 235B A22B"),
    ("cerebras", "qwen-3-32b", "Qwen3 32B"),
    ("cc", "claude-opus-5", "Claude Opus 5"),
    ("cc", "claude-fable-5-1", "Claude Fable 5.1"),
    ("cc", "claude-fable-5", "Claude Fable 5"),
    ("cc", "claude-sonnet-5", "Claude Sonnet 5"),
    ("cc", "claude-haiku-4-5-20251001", "Claude 4.5 Haiku"),
    ("cl", "anthropic/claude-opus-4.7", "Claude Opus 4.7"),
    ("cl", "anthropic/claude-sonnet-4.6", "Claude Sonnet 4.6"),
    ("cl", "anthropic/claude-opus-4.6", "Claude Opus 4.6"),
    ("cl", "openai/gpt-5.3-codex", "GPT-5.3 Codex"),
    ("cl", "openai/gpt-5.4", "GPT-5.4"),
    ("cl", "google/gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview"),
    ("cl", "google/gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview"),
    ("cl", "kwaipilot/kat-coder-pro", "KAT Coder Pro"),
    ("clinepass", "cline-pass/glm-5.2", "GLM-5.2 (ClinePass)"),
    ("clinepass", "cline-pass/kimi-k2.7-code", "Kimi K2.7 Code (ClinePass)"),
    ("clinepass", "cline-pass/kimi-k2.6", "Kimi K2.6 (ClinePass)"),
    ("clinepass", "cline-pass/deepseek-v4-pro", "DeepSeek V4 Pro (ClinePass)"),
    ("clinepass", "cline-pass/deepseek-v4-flash", "DeepSeek V4 Flash (ClinePass)"),
    ("clinepass", "cline-pass/mimo-v2.5", "MiMo-V2.5 (ClinePass)"),
    ("clinepass", "cline-pass/mimo-v2.5-pro", "MiMo-V2.5-Pro (ClinePass)"),
    ("clinepass", "cline-pass/minimax-m3", "MiniMax M3 (ClinePass)"),
    ("clinepass", "cline-pass/qwen3.7-max", "Qwen3.7 Max (ClinePass)"),
    ("clinepass", "cline-pass/qwen3.7-plus", "Qwen3.7 Plus (ClinePass)"),
    ("cloudflare-ai", "@cf/meta/llama-3.2-1b-instruct", "Llama 3.2 1B Instruct"),
    ("cloudflare-ai", "@cf/meta/llama-3.2-3b-instruct", "Llama 3.2 3B Instruct"),
    ("cloudflare-ai", "@cf/meta/llama-3.1-8b-instruct-fp8-fast", "Llama 3.1 8B Instruct FP8 Fast"),
    ("cloudflare-ai", "@cf/meta/llama-3.1-8b-instruct-awq", "Llama 3.1 8B Instruct AWQ"),
    ("cloudflare-ai", "@cf/mistralai/mistral-small-3.1-24b-instruct", "Mistral Small 3.1 24B Instruct"),
    ("cloudflare-ai", "@cf/meta/llama-3.1-70b-instruct-fp8-fast", "Llama 3.1 70B Instruct FP8 Fast"),
    ("cloudflare-ai", "@cf/meta/llama-3.3-70b-instruct-fp8-fast", "Llama 3.3 70B Instruct FP8 Fast"),
    ("cloudflare-ai", "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", "DeepSeek R1 Distill Qwen 32B"),
    ("cloudflare-ai", "@cf/moonshotai/kimi-k2.5", "Kimi K2.5"),
    ("cloudflare-ai", "@cf/moonshotai/kimi-k2.6", "Kimi K2.6"),
    ("cloudflare-ai", "@cf/zai-org/glm-4.7-flash", "GLM 4.7 Flash"),
    ("cloudflare-ai", "@cf/qwen/qwq-32b", "QwQ 32B"),
    ("cloudflare-ai", "@cf/qwen/qwen2.5-coder-32b-instruct", "Qwen 2.5 Coder 32B Instruct"),
    ("cloudflare-ai", "@cf/black-forest-labs/flux-2-klein-9b", "FLUX.2 Klein 9B"),
    ("cloudflare-ai", "@cf/black-forest-labs/flux-2-klein-4b", "FLUX.2 Klein 4B"),
    ("cloudflare-ai", "@cf/black-forest-labs/flux-2-dev", "FLUX.2 Dev"),
    ("cloudflare-ai", "@cf/leonardo/lucid-origin", "Lucid Origin"),
    ("cloudflare-ai", "@cf/leonardo/phoenix-1.0", "Phoenix 1.0"),
    ("cloudflare-ai", "@cf/black-forest-labs/flux-1-schnell", "FLUX.1 Schnell"),
    ("cloudflare-ai", "@cf/bytedance/stable-diffusion-xl-lightning", "SDXL Lightning"),
    ("cloudflare-ai", "@cf/lykon/dreamshaper-8-lcm", "DreamShaper 8 LCM"),
    ("cloudflare-ai", "@cf/runwayml/stable-diffusion-v1-5-img2img", "Stable Diffusion v1.5 Img2Img"),
    ("cloudflare-ai", "@cf/runwayml/stable-diffusion-v1-5-inpainting", "Stable Diffusion v1.5 Inpainting"),
    ("cloudflare-ai", "@cf/stabilityai/stable-diffusion-xl-base-1.0", "SDXL Base 1.0"),
    ("cbcn", "glm-5.2", "GLM-5.2"),
    ("cbcn", "glm-5.1", "GLM-5.1"),
    ("cbcn", "glm-5.0-turbo", "GLM-5.0-Turbo"),
    ("cbcn", "glm-5v-turbo", "GLM-5v-Turbo"),
    ("cbcn", "minimax-m3", "MiniMax-M3"),
    ("cbcn", "minimax-m2.7", "MiniMax-M2.7"),
    ("cbcn", "kimi-k2.7", "Kimi-K2.7-Code"),
    ("cbcn", "kimi-k2.6", "Kimi-K2.6"),
    ("cbcn", "kimi-k2.5", "Kimi-K2.5"),
    ("cbcn", "hy3-preview", "Hy3 Preview"),
    ("cbcn", "hy3", "Hy3"),
    ("cbcn", "hy3-x", "Hy3 (Paid)"),
    ("cbcn", "hy4-preview", "Hy4-Preview"),
    ("cbcn", "hy4-preview-x", "Hy4-Preview (Paid)"),
    ("cbcn", "glm-5.3", "GLM-5.3"),
    ("cbcn", "glm-5.3-flash", "GLM-5.3-Flash"),
    ("cbcn", "kimi-k3-1", "Kimi-K3"),
    ("cbcn", "deepseek-v4-pro", "DeepSeek-V4-Pro"),
    ("cbcn", "deepseek-v4-flash", "DeepSeek-V4-Flash"),
    ("cbcn", "deepseek-v3-2-volc", "DeepSeek-V3.2"),
    ("cx", "gpt-5.6-sol", "GPT 5.6 Sol"),
    ("cx", "gpt-5.6-sol-review", "GPT 5.6 Sol Review"),
    ("cx", "gpt-5.6-terra", "GPT 5.6 Terra"),
    ("cx", "gpt-5.6-terra-review", "GPT 5.6 Terra Review"),
    ("cx", "gpt-5.6-luna", "GPT 5.6 Luna"),
    ("cx", "gpt-5.6-luna-review", "GPT 5.6 Luna Review"),
    ("cx", "gpt-5.5", "GPT 5.5"),
    ("cx", "gpt-5.5-review", "GPT 5.5 Review"),
    ("cx", "gpt-5.4", "GPT 5.4"),
    ("cx", "gpt-5.4-review", "GPT 5.4 Review"),
    ("cx", "gpt-5.4-mini", "GPT 5.4 Mini"),
    ("cx", "gpt-5.4-mini-review", "GPT 5.4 Mini Review"),
    ("cx", "gpt-5.3-codex-spark", "GPT 5.3 Codex Spark"),
    ("cx", "gpt-5.3-codex-spark-review", "GPT 5.3 Codex Spark Review"),
    ("cx", "gpt-5.5-image", "GPT 5.5 Image"),
    ("cx", "gpt-5.4-image", "GPT 5.4 Image"),
    ("cx", "gpt-5.3-image", "GPT 5.3 Image"),
    ("cohere", "command-r-plus-08-2024", "Command R+ (Aug 2024)"),
    ("cohere", "command-r-08-2024", "Command R (Aug 2024)"),
    ("cohere", "command-a-03-2025", "Command A (Mar 2025)"),
    ("comfyui", "flux-dev", "FLUX Dev"),
    ("comfyui", "sdxl", "SDXL"),
    ("commandcode", "deepseek/deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("commandcode", "deepseek/deepseek-v4-flash", "DeepSeek V4 Flash"),
    ("commandcode", "moonshotai/Kimi-K2.6", "Kimi K2.6"),
    ("commandcode", "moonshotai/Kimi-K2.5", "Kimi K2.5"),
    ("commandcode", "zai-org/GLM-5.1", "GLM 5.1"),
    ("commandcode", "zai-org/GLM-5", "GLM 5"),
    ("commandcode", "MiniMaxAI/MiniMax-M2.7", "MiniMax M2.7"),
    ("commandcode", "MiniMaxAI/MiniMax-M2.5", "MiniMax M2.5"),
    ("commandcode", "Qwen/Qwen3.6-Max-Preview", "Qwen 3.6 Max Preview"),
    ("commandcode", "Qwen/Qwen3.6-Plus", "Qwen 3.6 Plus"),
    ("commandcode", "stepfun/Step-3.5-Flash", "Step 3.5 Flash"),
    ("cu", "default", "Auto (Server Picks)"),
    ("cu", "claude-4.5-opus-high-thinking", "Claude 4.5 Opus High Thinking"),
    ("cu", "claude-4.5-opus-high", "Claude 4.5 Opus High"),
    ("cu", "claude-4.5-sonnet-thinking", "Claude 4.5 Sonnet Thinking"),
    ("cu", "claude-4.5-sonnet", "Claude 4.5 Sonnet"),
    ("cu", "claude-4.5-haiku", "Claude 4.5 Haiku"),
    ("cu", "claude-4.5-opus", "Claude 4.5 Opus"),
    ("cu", "gpt-5.2-codex", "GPT 5.2 Codex"),
    ("cu", "claude-4.6-opus-max", "Claude 4.6 Opus Max"),
    ("cu", "claude-4.6-sonnet-medium-thinking", "Claude 4.6 Sonnet Medium Thinking"),
    ("cu", "kimi-k2.5", "Kimi K2.5"),
    ("cu", "gemini-3-flash-preview", "Gemini 3 Flash Preview"),
    ("cu", "gpt-5.2", "GPT 5.2"),
    ("cu", "gpt-5.3-codex", "GPT 5.3 Codex"),
    ("deepgram", "nova-3", "Nova 3"),
    ("deepgram", "nova-2", "Nova 2"),
    ("deepgram", "whisper-large", "Whisper Large"),
    ("deepgram", "nova", "Nova"),
    ("deepseek", "deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("deepseek", "deepseek-v4-pro-max", "DeepSeek V4 Pro Max"),
    ("deepseek", "deepseek-v4-pro-none", "DeepSeek V4 Pro No Thinking"),
    ("deepseek", "deepseek-v4-flash", "DeepSeek V4 Flash"),
    ("deepseek", "deepseek-v4-flash-vision-exp", "DeepSeek V4 Flash Vision (Exp)"),
    ("deepseek", "deepseek-chat", "DeepSeek V3.2 Chat"),
    ("deepseek", "deepseek-reasoner", "DeepSeek V3.2 Reasoner"),
    ("fal-ai", "fal-ai/flux/schnell", "FLUX Schnell"),
    ("fal-ai", "fal-ai/flux/dev", "FLUX Dev"),
    ("fal-ai", "fal-ai/flux-pro/v1.1", "FLUX Pro v1.1"),
    ("fal-ai", "fal-ai/flux-pro/v1.1-ultra", "FLUX Pro v1.1 Ultra"),
    ("fal-ai", "fal-ai/recraft-v3", "Recraft V3"),
    ("fal-ai", "fal-ai/ideogram/v2", "Ideogram V2"),
    ("fal-ai", "fal-ai/stable-diffusion-v35-large", "SD 3.5 Large"),
    ("featherless", "deepseek-ai/DeepSeek-V4-Pro", "DeepSeek V4 Pro"),
    ("featherless", "deepseek-ai/DeepSeek-V4-Flash", "DeepSeek V4 Flash"),
    ("featherless", "zai-org/GLM-5.2", "GLM 5.2"),
    ("featherless", "zai-org/GLM-5.1", "GLM 5.1"),
    ("featherless", "moonshotai/Kimi-K2.7-Code", "Kimi K2.7 Code"),
    ("featherless", "moonshotai/Kimi-K2.6", "Kimi K2.6"),
    ("featherless", "moonshotai/Kimi-K2.5", "Kimi K2.5"),
    ("fireworks", "accounts/fireworks/models/deepseek-v3p1", "DeepSeek V3.1"),
    ("fireworks", "accounts/fireworks/models/llama-v3p3-70b-instruct", "Llama 3.3 70B"),
    ("fireworks", "accounts/fireworks/models/qwen3-235b-a22b", "Qwen3 235B"),
    ("fireworks", "nomic-ai/nomic-embed-text-v1.5", "Nomic Embed Text v1.5"),
    ("gc", "gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview"),
    ("gc", "gemini-3-pro-preview", "Gemini 3 Pro Preview"),
    ("gc", "gemini-3-flash-preview", "Gemini 3 Flash Preview"),
    ("gc", "gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview"),
    ("gc", "gemini-2.5-pro", "Gemini 2.5 Pro"),
    ("gc", "gemini-2.5-flash", "Gemini 2.5 Flash"),
    ("gc", "gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite"),
    ("gemini", "gemini-3.8-flash", "Gemini 3.8 Flash"),
    ("gemini", "gemini-3.7-flash", "Gemini 3.7 Flash"),
    ("gemini", "gemini-3.6-flash", "Gemini 3.6 Flash"),
    ("gemini", "gemini-3.5-flash-lite", "Gemini 3.5 Flash Lite"),
    ("gemini", "gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview"),
    ("gemini", "gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview"),
    ("gemini", "gemini-3-flash-preview", "Gemini 3 Flash Preview"),
    ("gemini", "gemini-2.5-pro", "Gemini 2.5 Pro"),
    ("gemini", "gemini-2.5-flash", "Gemini 2.5 Flash"),
    ("gemini", "gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite"),
    ("gemini", "gemma-4-31b-it", "Gemma 4 31B IT"),
    ("gemini", "gemini-embedding-2-preview", "Gemini Embedding 2 Preview"),
    ("gemini", "gemini-embedding-001", "Gemini Embedding 001"),
    ("gemini", "text-embedding-005", "Text Embedding 005"),
    ("gemini", "text-embedding-004", "Text Embedding 004 (Legacy)"),
    ("gemini", "gemini-3.1-flash-image-preview", "Gemini 3.1 Flash Image (Nano Banana 2)"),
    ("gemini", "gemini-3-pro-image-preview", "Gemini 3 Pro Image (Nano Banana Pro)"),
    ("gemini", "gemini-2.5-flash-image", "Gemini 2.5 Flash Image (Nano Banana)"),
    ("gemini", "gemini-2.5-pro", "Gemini 2.5 Pro (Best)"),
    ("gemini", "gemini-2.5-flash", "Gemini 2.5 Flash"),
    ("gemini", "gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite (Cheapest)"),
    ("gemini", "gemini-2.0-flash", "Gemini 2.0 Flash"),
    ("gemini", "gemini-3.1-flash-tts-preview", "Gemini 3.1 Flash TTS"),
    ("gemini", "gemini-2.5-flash-preview-tts", "Gemini 2.5 Flash TTS"),
    ("gemini", "gemini-2.5-pro-preview-tts", "Gemini 2.5 Pro TTS"),
    ("gemini", "embedding-001", "Embedding 001"),
    ("gh", "gpt-5.2", "GPT-5.2"),
    ("gh", "gpt-5.2-codex", "GPT-5.2 Codex"),
    ("gh", "gpt-5.3-codex", "GPT-5.3 Codex"),
    ("gh", "gpt-5.4", "GPT-5.4"),
    ("gh", "gpt-5.4-mini", "GPT-5.4 Mini"),
    ("gh", "claude-haiku-4.5", "Claude Haiku 4.5"),
    ("gh", "claude-opus-4.5", "Claude Opus 4.5"),
    ("gh", "claude-sonnet-4.5", "Claude Sonnet 4.5"),
    ("gh", "claude-sonnet-4.6", "Claude Sonnet 4.6"),
    ("gh", "claude-opus-4.6", "Claude Opus 4.6"),
    ("gh", "claude-opus-4.7", "Claude Opus 4.7"),
    ("gh", "gemini-2.5-pro", "Gemini 2.5 Pro"),
    ("gh", "gemini-3-flash-preview", "Gemini 3 Flash"),
    ("gh", "gemini-3.1-pro-preview", "Gemini 3.1 Pro"),
    ("gh", "grok-code-fast-1", "Grok Code Fast 1"),
    ("gh", "oswe-vscode-prime", "Raptor Mini"),
    ("gh", "goldeneye-free-auto", "GoldenEye"),
    ("gh", "text-embedding-3-small", "Text Embedding 3 Small (GitHub)"),
    ("gh", "text-embedding-3-large", "Text Embedding 3 Large (GitHub)"),
    ("glm-cn", "glm-5.3", "GLM 5.3"),
    ("glm-cn", "glm-5.3-flash", "GLM 5.3 Flash (Vision)"),
    ("glm-cn", "glm-5.2", "GLM 5.2"),
    ("glm-cn", "glm-5.1", "GLM 5.1"),
    ("glm-cn", "glm-5", "GLM 5"),
    ("glm-cn", "glm-4.7", "GLM-4.7"),
    ("glm-cn", "glm-4.6v", "GLM 4.6V (Vision)"),
    ("glm-cn", "glm-4.6", "GLM-4.6"),
    ("glm-cn", "glm-4.5-air", "GLM-4.5-Air"),
    ("glm", "glm-5.3", "GLM 5.3"),
    ("glm", "glm-5.3-flash", "GLM 5.3 Flash (Vision)"),
    ("glm", "glm-5.2", "GLM 5.2"),
    ("glm", "glm-5.1", "GLM 5.1"),
    ("glm", "glm-5", "GLM 5"),
    ("glm", "glm-4.7", "GLM 4.7"),
    ("glm", "glm-4.6v", "GLM 4.6V (Vision)"),
    ("gcli", "grok-build", "Grok Build"),
    ("gcli", "grok-4.5", "Grok 4.5"),
    ("gcli", "grok-4.5-high", "Grok 4.5 (High)"),
    ("gcli", "grok-4.5-medium", "Grok 4.5 (Medium)"),
    ("gcli", "grok-4.5-low", "Grok 4.5 (Low)"),
    ("grok-web", "grok-3", "Grok 3"),
    ("grok-web", "grok-3-mini", "Grok 3 Mini (Thinking)"),
    ("grok-web", "grok-3-thinking", "Grok 3 Thinking"),
    ("grok-web", "grok-4", "Grok 4"),
    ("grok-web", "grok-4-mini", "Grok 4 Mini (Thinking)"),
    ("grok-web", "grok-4-thinking", "Grok 4 Thinking"),
    ("grok-web", "grok-4-heavy", "Grok 4 Heavy (SuperGrok)"),
    ("grok-web", "grok-4.1-mini", "Grok 4.1 Mini (Thinking)"),
    ("grok-web", "grok-4.1-fast", "Grok 4.1 Fast"),
    ("grok-web", "grok-4.1-expert", "Grok 4.1 Expert"),
    ("grok-web", "grok-4.1-thinking", "Grok 4.1 Thinking"),
    ("grok-web", "grok-4.2", "Grok 4.2 (4.20 Beta)"),
    ("groq", "llama-3.3-70b-versatile", "Llama 3.3 70B"),
    ("groq", "meta-llama/llama-4-maverick-17b-128e-instruct", "Llama 4 Maverick"),
    ("groq", "qwen/qwen3-32b", "Qwen3 32B"),
    ("groq", "openai/gpt-oss-120b", "GPT-OSS 120B"),
    ("groq", "whisper-large-v3", "Whisper Large v3"),
    ("groq", "whisper-large-v3-turbo", "Whisper Large v3 Turbo"),
    ("groq", "distil-whisper-large-v3-en", "Distil Whisper Large v3 EN"),
    ("huggingface", "black-forest-labs/FLUX.1-schnell", "FLUX.1 Schnell"),
    ("huggingface", "stabilityai/stable-diffusion-xl-base-1.0", "SDXL Base 1.0"),
    ("huggingface", "openai/whisper-large-v3", "Whisper Large v3 (HF)"),
    ("huggingface", "openai/whisper-small", "Whisper Small (HF)"),
    ("hyperbolic", "Qwen/QwQ-32B", "QwQ 32B"),
    ("hyperbolic", "deepseek-ai/DeepSeek-R1", "DeepSeek R1"),
    ("hyperbolic", "deepseek-ai/DeepSeek-V3", "DeepSeek V3"),
    ("hyperbolic", "meta-llama/Llama-3.3-70B-Instruct", "Llama 3.3 70B"),
    ("hyperbolic", "meta-llama/Llama-3.2-3B-Instruct", "Llama 3.2 3B"),
    ("hyperbolic", "Qwen/Qwen2.5-72B-Instruct", "Qwen 2.5 72B"),
    ("hyperbolic", "Qwen/Qwen2.5-Coder-32B-Instruct", "Qwen 2.5 Coder 32B"),
    ("hyperbolic", "NousResearch/Hermes-3-Llama-3.1-70B", "Hermes 3 70B"),
    ("if", "qwen3-coder-plus", "Qwen3 Coder Plus"),
    ("if", "qwen3-max", "Qwen3 Max"),
    ("if", "qwen3-vl-plus", "Qwen3 VL Plus"),
    ("if", "qwen3-max-preview", "Qwen3 Max Preview"),
    ("if", "qwen3-235b", "Qwen3 235B A22B"),
    ("if", "qwen3-235b-a22b-instruct", "Qwen3 235B A22B Instruct"),
    ("if", "qwen3-235b-a22b-thinking-2507", "Qwen3 235B A22B Thinking"),
    ("if", "qwen3-32b", "Qwen3 32B"),
    ("if", "kimi-k2", "Kimi K2"),
    ("if", "deepseek-v3.2", "DeepSeek V3.2 Exp"),
    ("if", "deepseek-v3.1", "DeepSeek V3.1 Terminus"),
    ("if", "deepseek-v3", "DeepSeek V3 671B"),
    ("if", "deepseek-r1", "DeepSeek R1"),
    ("if", "glm-4.7", "GLM 4.7"),
    ("if", "iflow-rome-30ba3b", "iFlow ROME"),
    ("kc", "anthropic/claude-sonnet-4-20250514", "Claude Sonnet 4"),
    ("kc", "anthropic/claude-opus-4-20250514", "Claude Opus 4"),
    ("kc", "google/gemini-2.5-pro", "Gemini 2.5 Pro"),
    ("kc", "google/gemini-2.5-flash", "Gemini 2.5 Flash"),
    ("kc", "openai/gpt-4.1", "GPT-4.1"),
    ("kc", "openai/o3", "o3"),
    ("kc", "deepseek/deepseek-chat", "DeepSeek Chat"),
    ("kc", "deepseek/deepseek-reasoner", "DeepSeek Reasoner"),
    ("kimchi", "minimax-m3", "MiniMax-M3"),
    ("kimchi", "kimi-k2.7", "Kimi-K2.7"),
    ("kimchi", "kimi-k2.6", "Kimi-K2.6"),
    ("kimchi", "kimi-k2.5", "Kimi-K2.5"),
    ("kimchi", "nemotron-3-ultra-fp4", "Nemotron 3 Ultra FP4"),
    ("kimchi", "minimax-m2.7", "MiniMax-M2.7"),
    ("kimchi", "claude-opus-4-6", "Claude Opus 4.6"),
    ("kimchi", "claude-sonnet-4-6", "Claude Sonnet 4.6"),
    ("kimi", "kimi-k3", "Kimi K3"),
    ("kimi", "k3", "Kimi K3 (Code)"),
    ("kimi", "kimi-for-coding", "Kimi for Coding"),
    ("kimi", "kimi-for-coding-highspeed", "Kimi for Coding Highspeed"),
    ("kimi", "kimi-k2.7-code", "Kimi K2.7 Code"),
    ("kimi", "kimi-k2.7-code-highspeed", "Kimi K2.7 Code Highspeed"),
    ("kimi", "kimi-k2.6", "Kimi K2.6"),
    ("kimi", "kimi-k2.5", "Kimi K2.5"),
    ("kimi", "kimi-k2.5-thinking", "Kimi K2.5 Thinking"),
    ("kimi", "kimi-latest", "Kimi Latest"),
    ("kr", "claude-opus-5", "Claude Opus 5"),
    ("kr", "claude-opus-5-thinking", "Claude Opus 5 (Thinking)"),
    ("kr", "claude-opus-5-agentic", "Claude Opus 5 (Agentic)"),
    ("kr", "claude-opus-5-thinking-agentic", "Claude Opus 5 (Thinking + Agentic)"),
    ("kr", "claude-opus-4.8", "Claude Opus 4.8"),
    ("kr", "claude-opus-4.8-thinking", "Claude Opus 4.8 (Thinking)"),
    ("kr", "claude-opus-4.8-agentic", "Claude Opus 4.8 (Agentic)"),
    ("kr", "claude-opus-4.8-thinking-agentic", "Claude Opus 4.8 (Thinking + Agentic)"),
    ("kr", "claude-opus-4.7", "Claude Opus 4.7"),
    ("kr", "claude-opus-4.7-thinking", "Claude Opus 4.7 (Thinking)"),
    ("kr", "claude-opus-4.7-agentic", "Claude Opus 4.7 (Agentic)"),
    ("kr", "claude-opus-4.7-thinking-agentic", "Claude Opus 4.7 (Thinking + Agentic)"),
    ("kr", "claude-opus-4.5", "Claude Opus 4.5"),
    ("kr", "claude-opus-4.5-thinking", "Claude Opus 4.5 (Thinking)"),
    ("kr", "claude-opus-4.5-agentic", "Claude Opus 4.5 (Agentic)"),
    ("kr", "claude-opus-4.5-thinking-agentic", "Claude Opus 4.5 (Thinking + Agentic)"),
    ("kr", "claude-sonnet-5", "Claude Sonnet 5"),
    ("kr", "claude-sonnet-4.5", "Claude Sonnet 4.5"),
    ("kr", "claude-haiku-4.5", "Claude Haiku 4.5"),
    ("kr", "deepseek-3.2", "DeepSeek 3.2"),
    ("kr", "qwen3-coder-next", "Qwen3 Coder Next"),
    ("kr", "glm-5", "GLM 5"),
    ("kr", "MiniMax-M2.5", "MiniMax M2.5"),
    ("kr", "gpt-5.6-sol", "GPT 5.6 Sol"),
    ("kr", "gpt-5.6-terra", "GPT 5.6 Terra"),
    ("kr", "gpt-5.6-luna", "GPT 5.6 Luna"),
    ("kr", "claude-sonnet-5-thinking", "Claude Sonnet 5 (Thinking)"),
    ("kr", "claude-sonnet-4.5-thinking", "Claude Sonnet 4.5 (Thinking)"),
    ("kr", "claude-haiku-4.5-thinking", "Claude Haiku 4.5 (Thinking)"),
    ("kr", "gpt-5.6-sol-thinking", "GPT 5.6 Sol (Thinking)"),
    ("kr", "gpt-5.6-terra-thinking", "GPT 5.6 Terra (Thinking)"),
    ("kr", "gpt-5.6-luna-thinking", "GPT 5.6 Luna (Thinking)"),
    ("kr", "claude-sonnet-5-agentic", "Claude Sonnet 5 (Agentic)"),
    ("kr", "claude-sonnet-4.5-agentic", "Claude Sonnet 4.5 (Agentic)"),
    ("kr", "claude-haiku-4.5-agentic", "Claude Haiku 4.5 (Agentic)"),
    ("kr", "gpt-5.6-sol-agentic", "GPT 5.6 Sol (Agentic)"),
    ("kr", "gpt-5.6-terra-agentic", "GPT 5.6 Terra (Agentic)"),
    ("kr", "gpt-5.6-luna-agentic", "GPT 5.6 Luna (Agentic)"),
    ("kr", "claude-sonnet-5-thinking-agentic", "Claude Sonnet 5 (Thinking + Agentic)"),
    ("kr", "claude-sonnet-4.5-thinking-agentic", "Claude Sonnet 4.5 (Thinking + Agentic)"),
    ("kr", "claude-haiku-4.5-thinking-agentic", "Claude Haiku 4.5 (Thinking + Agentic)"),
    ("kr", "gpt-5.6-sol-thinking-agentic", "GPT 5.6 Sol (Thinking + Agentic)"),
    ("kr", "gpt-5.6-terra-thinking-agentic", "GPT 5.6 Terra (Thinking + Agentic)"),
    ("kr", "gpt-5.6-luna-thinking-agentic", "GPT 5.6 Luna (Thinking + Agentic)"),
    ("mmf", "mimo-auto", "MiMo Auto"),
    ("minimax-cn", "MiniMax-M3", "MiniMax M3"),
    ("minimax-cn", "MiniMax-M2.7", "MiniMax M2.7"),
    ("minimax-cn", "MiniMax-M2.5", "MiniMax M2.5"),
    ("minimax-cn", "MiniMax-M2.1", "MiniMax M2.1"),
    ("minimax-cn", "speech-2.8-hd", "Speech 2.8 HD"),
    ("minimax-cn", "speech-2.8-turbo", "Speech 2.8 Turbo"),
    ("minimax-cn", "speech-2.6-hd", "Speech 2.6 HD"),
    ("minimax-cn", "speech-2.6-turbo", "Speech 2.6 Turbo"),
    ("minimax-cn", "speech-02-hd", "Speech 02 HD"),
    ("minimax-cn", "speech-02-turbo", "Speech 02 Turbo"),
    ("minimax-cn", "speech-01-hd", "Speech 01 HD"),
    ("minimax-cn", "speech-01-turbo", "Speech 01 Turbo"),
    ("minimax", "MiniMax-M3", "MiniMax M3"),
    ("minimax", "MiniMax-M2.7", "MiniMax M2.7"),
    ("minimax", "MiniMax-M2.5", "MiniMax M2.5"),
    ("minimax", "MiniMax-M2.1", "MiniMax M2.1"),
    ("minimax", "minimax-image-01", "MiniMax Image 01"),
    ("minimax", "speech-2.8-hd", "Speech 2.8 HD"),
    ("minimax", "speech-2.8-turbo", "Speech 2.8 Turbo"),
    ("minimax", "speech-2.6-hd", "Speech 2.6 HD"),
    ("minimax", "speech-2.6-turbo", "Speech 2.6 Turbo"),
    ("minimax", "speech-02-hd", "Speech 02 HD"),
    ("minimax", "speech-02-turbo", "Speech 02 Turbo"),
    ("minimax", "speech-01-hd", "Speech 01 HD"),
    ("minimax", "speech-01-turbo", "Speech 01 Turbo"),
    ("mistral", "mistral-large-latest", "Mistral Large 3"),
    ("mistral", "codestral-latest", "Codestral"),
    ("mistral", "mistral-medium-latest", "Mistral Medium 3"),
    ("mistral", "mistral-embed", "Mistral Embed"),
    ("nanobanana", "nanobanana-flash", "NanoBanana Flash"),
    ("nanobanana", "nanobanana-pro", "NanoBanana Pro"),
    ("nebius", "meta-llama/Llama-3.3-70B-Instruct", "Llama 3.3 70B Instruct"),
    ("nebius", "Qwen/Qwen3-Embedding-8B", "Qwen3 Embedding 8B"),
    ("nvidia", "minimaxai/minimax-m2.7", "MiniMax M2.7"),
    ("nvidia", "minimaxai/minimax-m3", "MiniMax M3"),
    ("nvidia", "z-ai/glm-5.2", "GLM 5.2"),
    ("nvidia", "deepseek-ai/deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("nvidia", "deepseek-ai/deepseek-v4-flash", "DeepSeek V4 Flash"),
    ("nvidia", "moonshotai/kimi-k2.6", "Kimi K2.6"),
    ("nvidia", "nvidia/nemotron-3-ultra-550b-a55b", "Nemotron 3 Ultra"),
    ("nvidia", "nvidia/nv-embedqa-e5-v5", "NV EmbedQA E5 v5"),
    ("nvidia", "nvidia/parakeet-ctc-1.1b-asr", "Parakeet CTC 1.1B"),
    ("nvidia", "fastpitch", "FastPitch"),
    ("nvidia", "tacotron2", "Tacotron2"),
    ("ollama", "gpt-oss:120b", "GPT OSS 120B"),
    ("ollama", "kimi-k2.5", "Kimi K2.5"),
    ("ollama", "glm-5", "GLM 5"),
    ("ollama", "minimax-m2.5", "MiniMax M2.5"),
    ("ollama", "glm-4.7-flash", "GLM 4.7 Flash"),
    ("ollama", "qwen3.5", "Qwen3.5"),
    ("ollama", "minimax-m3", "MiniMax M3"),
    ("openai", "gpt-5.4", "GPT-5.4"),
    ("openai", "gpt-5.4-mini", "GPT-5.4 Mini"),
    ("openai", "gpt-5.4-nano", "GPT-5.4 Nano"),
    ("openai", "gpt-5.2", "GPT-5.2"),
    ("openai", "gpt-5.1", "GPT-5.1"),
    ("openai", "gpt-5", "GPT-5"),
    ("openai", "gpt-5-mini", "GPT-5 Mini"),
    ("openai", "gpt-5-nano", "GPT-5 Nano"),
    ("openai", "gpt-4o", "GPT-4o"),
    ("openai", "gpt-4o-mini", "GPT-4o Mini"),
    ("openai", "gpt-4-turbo", "GPT-4 Turbo"),
    ("openai", "gpt-4.1", "GPT-4.1"),
    ("openai", "gpt-4.1-mini", "GPT-4.1 Mini"),
    ("openai", "gpt-4.1-nano", "GPT-4.1 Nano"),
    ("openai", "o3", "O3"),
    ("openai", "o3-mini", "O3 Mini"),
    ("openai", "o3-pro", "O3 Pro"),
    ("openai", "o4-mini", "O4 Mini"),
    ("openai", "o1", "O1"),
    ("openai", "o1-mini", "O1 Mini"),
    ("openai", "text-embedding-3-large", "Text Embedding 3 Large"),
    ("openai", "text-embedding-3-small", "Text Embedding 3 Small"),
    ("openai", "text-embedding-ada-002", "Text Embedding Ada 002"),
    ("openai", "tts-1", "TTS-1"),
    ("openai", "tts-1-hd", "TTS-1 HD"),
    ("openai", "gpt-4o-mini-tts", "GPT-4o Mini TTS"),
    ("openai", "whisper-1", "Whisper 1"),
    ("openai", "gpt-4o-transcribe", "GPT-4o Transcribe"),
    ("openai", "gpt-4o-mini-transcribe", "GPT-4o Mini Transcribe"),
    ("openai", "gpt-image-1", "GPT Image 1"),
    ("openai", "dall-e-3", "DALL-E 3"),
    ("openai", "dall-e-2", "DALL-E 2"),
    ("opencode-go", "glm-5.3-flash", "GLM 5.3 Flash (Vision)"),
    ("opencode-go", "glm-5.2", "GLM 5.2"),
    ("opencode-go", "glm-5.1", "GLM 5.1"),
    ("opencode-go", "kimi-k2.7-code", "Kimi K2.7 Code"),
    ("opencode-go", "kimi-k2.6", "Kimi K2.6"),
    ("opencode-go", "deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("opencode-go", "deepseek-v4-flash", "DeepSeek V4 Flash"),
    ("opencode-go", "deepseek-v4-flash-vision-exp", "DeepSeek V4 Flash Vision (Exp)"),
    ("opencode-go", "mimo-v2.5", "MiMo V2.5"),
    ("opencode-go", "mimo-v2.5-pro", "MiMo V2.5 Pro"),
    ("opencode-go", "minimax-m3", "MiniMax M3"),
    ("opencode-go", "minimax-m2.7", "MiniMax M2.7"),
    ("opencode-go", "minimax-m2.5", "MiniMax M2.5"),
    ("opencode-go", "qwen3.7-max", "Qwen 3.7 Max"),
    ("opencode-go", "qwen3.7-plus", "Qwen 3.7 Plus"),
    ("opencode-go", "qwen3.6-plus", "Qwen 3.6 Plus"),
    ("oc", "muse-spark-1.2-contributor-free", "Muse Spark 1.2 Contributor Free"),
    ("oc", "muse-spark-1.3-contributor-free", "Muse Spark 1.3 Contributor Free"),
    ("openrouter", "openai/text-embedding-3-large", "OpenAI Text Embedding 3 Large"),
    ("openrouter", "openai/text-embedding-3-small", "OpenAI Text Embedding 3 Small"),
    ("openrouter", "openai/text-embedding-ada-002", "OpenAI Text Embedding Ada 002"),
    ("openrouter", "qwen/qwen3-embedding-8b", "Qwen3 Embedding 8B"),
    ("openrouter", "perplexity/pplx-embed-v1-4b", "Perplexity Embed V1 4B"),
    ("openrouter", "perplexity/pplx-embed-v1-0.6b", "Perplexity Embed V1 0.6B"),
    ("openrouter", "nvidia/llama-nemotron-embed-vl-1b-v2:free", "NVIDIA Nemotron Embed VL 1B V2 (Free)"),
    ("openrouter", "openai/gpt-4o-mini-tts", "GPT-4o Mini TTS"),
    ("openrouter", "openai/tts-1-hd", "TTS-1 HD"),
    ("openrouter", "openai/tts-1", "TTS-1"),
    ("openrouter", "openai/dall-e-3", "DALL-E 3 (via OpenRouter)"),
    ("openrouter", "openai/gpt-image-1", "GPT Image 1 (via OpenRouter)"),
    ("openrouter", "google/imagen-3.0-generate-002", "Imagen 3 (via OpenRouter)"),
    ("openrouter", "black-forest-labs/FLUX.1-schnell", "FLUX.1 Schnell (via OpenRouter)"),
    ("perplexity-web", "pplx-auto", "Perplexity Auto (Free)"),
    ("perplexity-web", "pplx-sonar", "Perplexity Sonar"),
    ("perplexity-web", "pplx-gpt", "GPT-5.4 (via Perplexity)"),
    ("perplexity-web", "pplx-gemini", "Gemini 3.1 Pro (via Perplexity)"),
    ("perplexity-web", "pplx-sonnet", "Claude Sonnet 4.6 (via Perplexity)"),
    ("perplexity-web", "pplx-opus", "Claude Opus 4.6 (via Perplexity)"),
    ("perplexity-web", "pplx-nemotron", "Nemotron 3 Super (via Perplexity)"),
    ("perplexity", "sonar-pro", "Sonar Pro"),
    ("perplexity", "sonar", "Sonar"),
    ("perplexity-agent", "perplexity/sonar", "Perplexity Sonar"),
    ("perplexity-agent", "openai/gpt-5.5", "GPT-5.5"),
    ("perplexity-agent", "openai/gpt-5.4", "GPT-5.4"),
    ("perplexity-agent", "openai/gpt-5.4-mini", "GPT-5.4 Mini"),
    ("perplexity-agent", "anthropic/claude-sonnet-4-6", "Claude Sonnet 4.6"),
    ("perplexity-agent", "anthropic/claude-opus-4-8", "Claude Opus 4.8"),
    ("perplexity-agent", "google/gemini-3.1-pro-preview", "Gemini 3.1 Pro"),
    ("perplexity-agent", "xai/grok-4.20-reasoning", "Grok 4.20 Reasoning"),
    ("perplexity-agent", "perplexity/glm-5.2", "GLM 5.2"),
    ("perplexity-agent", "perplexity/kimi-k2.7-code", "Kimi K2.7 Code"),
    ("perplexity-agent", "nvidia/nemotron-3-super-120b-a12b", "Nemotron 3 Super 120B"),
    ("qd", "ultimate", "Ultimate"),
    ("qd", "auto", "Auto"),
    ("qd", "performance", "Performance"),
    ("qd", "efficient", "Efficient"),
    ("qd", "qmodel_preview", "Qwen3.8-Max-Preview"),
    ("qd", "qmodel_latest", "Qwen3.7-Max"),
    ("qd", "qmodel", "Qwen3.7-Plus"),
    ("qd", "kmodel_latest", "Kimi-K3"),
    ("qd", "kmodel", "Kimi-K2.7-Code"),
    ("qd", "gm51model", "GLM-5.2"),
    ("qd", "dmodel", "DeepSeek-V4-Pro"),
    ("qd", "dfmodel", "DeepSeek-V4-Flash"),
    ("qd", "mmodel", "MiniMax-M3"),
    ("recraft", "recraftv3", "Recraft V3"),
    ("recraft", "recraftv2", "Recraft V2"),
    ("runwayml", "gen4_image", "Gen-4 Image"),
    ("runwayml", "gen4_image_turbo", "Gen-4 Image Turbo"),
    ("runwayml", "gen4_turbo", "Gen-4 Turbo"),
    ("runwayml", "gen3a_turbo", "Gen-3 Alpha Turbo"),
    ("sdwebui", "stable-diffusion-v1-5", "Stable Diffusion v1.5"),
    ("sdwebui", "sdxl-base-1.0", "SDXL Base 1.0"),
    ("siliconflow", "deepseek-ai/DeepSeek-V4-Pro", "DeepSeek V4 Pro"),
    ("siliconflow", "deepseek-ai/DeepSeek-V4-Flash", "DeepSeek V4 Flash"),
    ("siliconflow", "deepseek-ai/DeepSeek-V3.2", "DeepSeek V3.2"),
    ("siliconflow", "deepseek-ai/DeepSeek-V3.2-Exp", "DeepSeek V3.2 Exp"),
    ("siliconflow", "deepseek-ai/DeepSeek-V3.1", "DeepSeek V3.1"),
    ("siliconflow", "deepseek-ai/DeepSeek-V3.1-Terminus", "DeepSeek V3.1 Terminus"),
    ("siliconflow", "deepseek-ai/DeepSeek-R1", "DeepSeek R1"),
    ("siliconflow", "Qwen/Qwen3.5-397B-A17B", "Qwen 3.5 397B A17B"),
    ("siliconflow", "Qwen/Qwen3.5-122B-A10B", "Qwen 3.5 122B A10B"),
    ("siliconflow", "zai-org/GLM-5.1", "GLM 5.1"),
    ("siliconflow", "zai-org/GLM-5", "GLM 5"),
    ("siliconflow", "moonshotai/Kimi-K2.6", "Kimi K2.6"),
    ("siliconflow", "moonshotai/Kimi-K2.5", "Kimi K2.5"),
    ("siliconflow", "openai/gpt-oss-120b", "GPT OSS 120B"),
    ("siliconflow", "MiniMaxAI/MiniMax-M2.5", "MiniMax M2.5"),
    ("siliconflow", "inclusionAI/Ling-flash-2.0", "Ling Flash 2.0"),
    ("stability-ai", "stable-image-ultra", "Stable Image Ultra"),
    ("stability-ai", "stable-image-core", "Stable Image Core"),
    ("stability-ai", "sd3.5-large", "Stable Diffusion 3.5 Large"),
    ("stability-ai", "sd3.5-large-turbo", "Stable Diffusion 3.5 Large Turbo"),
    ("stability-ai", "sd3.5-medium", "Stable Diffusion 3.5 Medium"),
    ("together", "meta-llama/Llama-3.3-70B-Instruct-Turbo", "Llama 3.3 70B Turbo"),
    ("together", "deepseek-ai/DeepSeek-R1", "DeepSeek R1"),
    ("together", "Qwen/Qwen3-235B-A22B", "Qwen3 235B"),
    ("together", "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", "Llama 4 Maverick"),
    ("together", "BAAI/bge-large-en-v1.5", "BGE Large EN v1.5"),
    ("together", "togethercomputer/m2-bert-80M-8k-retrieval", "M2 BERT 80M 8K"),
    ("venice", "venice-uncensored-1-2", "Venice Uncensored 1.2"),
    ("venice", "zai-org-glm-5", "GLM-5"),
    ("venice", "qwen3-235b-a22b-instruct-2507", "Qwen3 235B A22B Instruct"),
    ("venice", "qwen3-coder-480b-a35b-instruct-turbo", "Qwen3 Coder 480B A35B Turbo"),
    ("venice", "qwen3-vl-235b-a22b", "Qwen3 VL 235B A22B"),
    ("venice", "deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("venice", "llama-3.3-70b", "Llama 3.3 70B"),
    ("venice", "hermes-3-llama-3.1-405b", "Hermes 3 Llama 3.1 405B"),
    ("venice", "mistral-small-3-2-24b-instruct", "Mistral Small 3.2 24B"),
    ("venice", "text-embedding-3-large", "Text Embedding 3 Large"),
    ("venice", "text-embedding-bge-m3", "BGE-M3 Embedding"),
    ("venice", "text-embedding-qwen3-8b", "Qwen3 8B Embedding"),
    ("venice", "venice-sd35", "Venice SD3.5"),
    ("venice", "flux-2-pro", "FLUX.2 Pro"),
    ("venice", "gpt-image-2", "GPT Image 2 (via Venice)"),
    ("vertex-partner", "deepseek-ai/deepseek-v3.2-maas", "DeepSeek V3.2 (Vertex)"),
    ("vertex-partner", "qwen/qwen3-next-80b-a3b-thinking-maas", "Qwen3 Next 80B Thinking (Vertex)"),
    ("vertex-partner", "qwen/qwen3-next-80b-a3b-instruct-maas", "Qwen3 Next 80B Instruct (Vertex)"),
    ("vertex-partner", "zai-org/glm-5-maas", "GLM-5 (Vertex)"),
    ("vertex", "gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview"),
    ("vertex", "gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview"),
    ("vertex", "gemini-3-flash-preview", "Gemini 3 Flash Preview"),
    ("vertex", "gemini-2.5-flash", "Gemini 2.5 Flash"),
    ("volcengine-ark", "Doubao-Seed-2.0-Code", "Doubao-Seed-2.0-Code"),
    ("volcengine-ark", "Doubao-Seed-2.0-pro", "Doubao-Seed-2.0-pro"),
    ("volcengine-ark", "Doubao-Seed-2.0-lite", "Doubao-Seed-2.0-lite"),
    ("volcengine-ark", "Doubao-Seed-Code", "Doubao-Seed-Code"),
    ("volcengine-ark", "DeepSeek-V4-Flash", "DeepSeek-V4-Flash"),
    ("volcengine-ark", "DeepSeek-V4-Pro", "DeepSeek-V4-Pro"),
    ("volcengine-ark", "GLM-5.1", "GLM-5.1"),
    ("volcengine-ark", "MiniMax-M2.7", "MiniMax-M2.7"),
    ("volcengine-ark", "Kimi-K2.6", "Kimi-K2.6"),
    ("voyage-ai", "voyage-3-large", "Voyage 3 Large"),
    ("voyage-ai", "voyage-3.5", "Voyage 3.5"),
    ("voyage-ai", "voyage-3.5-lite", "Voyage 3.5 Lite"),
    ("voyage-ai", "voyage-code-3", "Voyage Code 3"),
    ("voyage-ai", "voyage-finance-2", "Voyage Finance 2"),
    ("voyage-ai", "voyage-law-2", "Voyage Law 2"),
    ("voyage-ai", "voyage-multilingual-2", "Voyage Multilingual 2"),
    ("xai", "grok-4.6", "Grok 4.6"),
    ("xai", "grok-4.5", "Grok 4.5"),
    ("xai", "grok-4", "Grok 4"),
    ("xai", "grok-4-fast-reasoning", "Grok 4 Fast Reasoning"),
    ("xai", "grok-code-fast-1", "Grok Code Fast"),
    ("xai", "grok-3", "Grok 3"),
    ("xai", "grok-2-image-1212", "Grok 2 Image"),
    ("xai", "grok-imagine-video", "Grok Imagine Video"),
    ("xiaomi-mimo", "mimo-v2.5-pro", "MiMo V2.5 Pro"),
    ("xiaomi-mimo", "mimo-v2.5", "MiMo V2.5"),
    ("xiaomi-mimo", "mimo-v2-omni", "MiMo V2 Omni"),
    ("xiaomi-mimo", "mimo-v2-flash", "MiMo V2 Flash"),
    ("xiaomi-mimo", "mimo-v2.5-tts", "MiMo V2.5 TTS"),
    ("xiaomi-tokenplan", "mimo-v2.5-pro", "MiMo V2.5 Pro"),
    ("xiaomi-tokenplan", "mimo-v2.5-pro-claude", "MiMo V2.5 Pro (Claude Native)"),
    ("xiaomi-tokenplan", "mimo-v2.5", "MiMo V2.5"),
    ("xiaomi-tokenplan", "mimo-v2-pro", "MiMo V2 Pro"),
    ("xiaomi-tokenplan", "mimo-v2-omni", "MiMo V2 Omni"),
    ("xiaomi-tokenplan", "mimo-v2-tts", "MiMo V2 TTS"),
    ("xiaomi-tokenplan", "mimo-v2.5-tts", "MiMo V2.5 TTS"),
    ("xiaomi-tokenplan", "mimo-v2.5-tts-voiceclone", "MiMo V2.5 TTS Voice Clone"),
    ("xiaomi-tokenplan", "mimo-v2.5-tts-voicedesign", "MiMo V2.5 TTS Voice Design"),
    ("alims-intl", "qwen3.5-plus", "Qwen3.5 Plus"),
    ("alims-intl", "kimi-k2.5", "Kimi K2.5"),
    ("alims-intl", "glm-5", "GLM 5"),
    ("alims-intl", "MiniMax-M2.5", "MiniMax M2.5"),
    ("alims-intl", "qwen3-coder-next", "Qwen3 Coder Next"),
    ("alims-intl", "qwen3-coder-plus", "Qwen3 Coder Plus"),
    ("alims-intl", "glm-4.7", "GLM 4.7"),
    ("cbai", "glm-5.2", "GLM-5.2"),
    ("cbai", "glm-5.1", "GLM-5.1"),
    ("cbai", "glm-5.0", "GLM-5.0"),
    ("cbai", "glm-5.0-turbo", "GLM-5.0-Turbo"),
    ("cbai", "glm-5v-turbo", "GLM-5v-Turbo"),
    ("cbai", "glm-4.7", "GLM-4.7"),
    ("cbai", "minimax-m3", "MiniMax-M3"),
    ("cbai", "minimax-m2.7", "MiniMax-M2.7"),
    ("cbai", "kimi-k2.7", "Kimi-K2.7-Code"),
    ("cbai", "kimi-k2.6", "Kimi-K2.6"),
    ("cbai", "kimi-k2.5", "Kimi-K2.5"),
    ("cbai", "hy3-preview", "Hy3 Preview"),
    ("cbai", "deepseek-v4-pro", "DeepSeek-V4-Pro"),
    ("cbai", "deepseek-v4-flash", "DeepSeek-V4-Flash"),
    ("cbai", "deepseek-v3-2-volc", "DeepSeek-V3.2"),
    ("af", "anthropic/claude-3.7-sonnet", "Claude 3.7 Sonnet (Free)"),
    ("af", "moonshot/kimi-k2.6", "Kimi K2.6 (Free)"),
    ("af", "google/gemini-2.5-flash", "Gemini 2.5 Flash (Free)"),
    ("qianfan", "deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("qianfan", "deepseek-v4-flash", "DeepSeek V4 Flash"),
    ("qianfan", "glm-5.2", "GLM 5.2"),
    ("qianfan", "glm-5.1", "GLM 5.1"),
    ("qianfan", "kimi-k2.6", "Kimi K2.6"),
    ("qianfan", "qwen3.5-397b-a17b", "Qwen 3.5 397B A17B"),
    ("qianfan", "qwen3.5-27b", "Qwen 3.5 27B"),
    ("bzl", "auto:free", "Auto Free (Zero Cost)"),
    ("bzl", "claude-opus-4.7", "Claude Opus 4.7"),
    ("bzl", "claude-sonnet-4.6", "Claude Sonnet 4.6"),
    ("bzl", "claude-haiku-4.5", "Claude Haiku 4.5"),
    ("bzl", "gpt-5.5", "GPT-5.5"),
    ("bzl", "gpt-5.4", "GPT-5.4"),
    ("bzl", "gpt-5.4-mini", "GPT-5.4 Mini"),
    ("bzl", "gpt-5.4-nano", "GPT-5.4 Nano"),
    ("bzl", "grok-4.3", "Grok 4.3"),
    ("bzl", "grok-4.20", "Grok 4.20"),
    ("bzl", "gemini-3.1-pro-preview", "Gemini 3.1 Pro"),
    ("bzl", "gemini-3-flash-preview", "Gemini 3 Flash"),
    ("bzl", "gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite"),
    ("bzl", "kimi-k2.6", "Kimi K2.6"),
    ("bzl", "kimi-k2.5", "Kimi K2.5"),
    ("bzl", "glm-5.1", "GLM 5.1"),
    ("bzl", "glm-5", "GLM 5"),
    ("bzl", "mimo-v2.5-pro", "MiMo-V2.5-Pro"),
    ("bzl", "mimo-v2.5", "MiMo-V2.5"),
    ("bzl", "minimax-m3", "MiniMax M3"),
    ("bzl", "minimax-m2.7", "MiniMax M2.7"),
    ("bzl", "minimax-m2.5", "MiniMax M2.5"),
    ("bzl", "qwen3.6-plus", "Qwen 3.6 Plus"),
    ("bzl", "nemotron-3-super-120b-a12b", "Nemotron 3 Super"),
    ("bm", "gpt-4.1", "GPT-4.1"),
    ("bm", "gpt-4.1-mini", "GPT-4.1 Mini"),
    ("bm", "gpt-4.1-nano", "GPT-4.1 Nano"),
    ("bm", "claude-sonnet-4-5", "Claude Sonnet 4.5"),
    ("bm", "claude-haiku-4-5", "Claude Haiku 4.5"),
    ("bm", "gemini-2.0-flash", "Gemini 2.0 Flash"),
    ("bm", "gemini-2.0-flash-exp", "Gemini 2.0 Flash (Exp)"),
    ("bm", "qwen-turbo", "Qwen Turbo"),
    ("bm", "kimi-k2", "Kimi K2"),
    ("bm", "kimi-k2-thinking", "Kimi K2 Thinking"),
    ("bm", "glm-4.7", "GLM 4.7"),
    ("bm", "minimax-m2.5", "MiniMax M2.5"),
    ("bm", "claude-opus-4-5", "Claude Opus 4.5 (VIP)"),
    ("bm", "gemini-2.5-pro", "Gemini 2.5 Pro (VIP)"),
    ("kgw", "kilo-auto/free", "Kilo Auto Free"),
    ("kgw", "nvidia/nemotron-3-super-120b-a12b:free", "Nemotron 3 Super 120B (Free)"),
    ("kgw", "nvidia/nemotron-3-ultra-550b-a55b:free", "Nemotron 3 Ultra 550B (Free)"),
    ("kgw", "kwaipilot/kat-coder-pro-v2.5:free", "Kat Coder Pro v2.5 (Free)"),
    ("kgw", "kilo-auto/frontier", "Kilo Auto Frontier"),
    ("kgw", "kilo-auto/balanced", "Kilo Auto Balanced"),
    ("llm7", "gpt-5.5", "GPT-5.5 (LLM7)"),
    ("llm7", "claude-opus-5", "Claude Opus 5 (LLM7)"),
    ("llm7", "deepseek-v4-flash", "DeepSeek V4 Flash (LLM7)"),
    ("llm7", "grok-4.5", "Grok 4.5 (LLM7)"),
    ("llm7", "kimi-k3", "Kimi K3 (LLM7)"),
    ("samba", "MiniMax-M2.7", "MiniMax M2.7"),
    ("hunyuan", "hunyuan-turbos-latest", "Hunyuan TurboS Latest"),
    ("hunyuan", "hunyuan-t1-latest", "Hunyuan T1 Latest"),
    ("morph", "morph-v3-large", "Morph v3 Large"),
    ("morph", "morph-v3-fast", "Morph v3 Fast"),
    ("morph", "morph-qwen35-397b", "Qwen 3.5 397B (Morph)"),
    ("morph", "morph-minimax27-230b", "MiniMax M2.7 (Morph)"),
    ("morph", "morph-qwen36-27b", "Qwen 3.6 27B (Morph)"),
    ("morph", "morph-dsv4flash", "DeepSeek V4 Flash (Morph)"),
    ("poolside", "poolside/laguna-s-2.1", "Laguna S 2.1"),
    ("poolside", "poolside/laguna-xs-2.1", "Laguna XS 2.1"),
    ("tokenrouter", "anthropic/claude-haiku-4.5", "Claude Haiku 4.5"),
    ("tokenrouter", "anthropic/claude-sonnet-4.6", "Claude Sonnet 4.6"),
    ("tokenrouter", "anthropic/claude-opus-4.8", "Claude Opus 4.8"),
    ("tokenrouter", "anthropic/claude-opus-4.8-fast", "Claude Opus 4.8 Fast"),
    ("tokenrouter", "openai/gpt-5.4", "Gpt 5.4"),
    ("tokenrouter", "openai/gpt-5.4-mini", "Gpt 5.4 Mini"),
    ("tokenrouter", "openai/gpt-5.4-pro", "Gpt 5.4 Pro"),
    ("tokenrouter", "openai/gpt-5.5", "Gpt 5.5"),
    ("tokenrouter", "openai/gpt-5.6-sol", "Gpt 5.6 Sol"),
    ("tokenrouter", "google/gemini-3.5-flash", "Gemini 3.5 Flash"),
    ("tokenrouter", "google/gemini-3.6-flash", "Gemini 3.6 Flash"),
    ("tokenrouter", "deepseek/deepseek-v4-flash", "Deepseek V4 Flash"),
    ("tokenrouter", "deepseek/deepseek-v4-pro", "Deepseek V4 Pro"),
    ("tokenrouter", "qwen/qwen3-coder-next", "Qwen3 Coder Next"),
    ("tokenrouter", "qwen/qwen3.7-max", "Qwen3.7 Max"),
    ("tokenrouter", "qwen/qwen3.8-max", "Qwen3.8 Max"),
    ("tokenrouter", "moonshotai/kimi-k2.7-code", "Kimi K2.7 Code"),
    ("tokenrouter", "moonshotai/kimi-k3-free", "Kimi K3 Free"),
    ("tokenrouter", "z-ai/glm-5.3-free", "Glm 5.3 Free"),
    ("tokenrouter", "z-ai/glm-5.2", "Glm 5.2"),
    ("tokenrouter", "z-ai/glm-5-turbo", "Glm 5 Turbo"),
    ("tokenrouter", "x-ai/grok-4.5", "Grok 4.5"),
    ("selfhosted-stt", "whisper-1", "Whisper (self-hosted)"),
    ("selfhosted-tts", "kokoro", "Kokoro (self-hosted)"),
    ("selfhosted-embedding", "embedding", "Self-hosted embedding model"),
    ("alitp-intl", "qwen3.8-max-preview", "Qwen3.8 Max Preview"),
    ("alitp-intl", "qwen3.7-max", "Qwen3.7 Max"),
    ("alitp-intl", "qwen3.7-plus", "Qwen3.7 Plus"),
    ("alitp-intl", "qwen3.6-flash", "Qwen3.6 Flash"),
    ("alitp-intl", "glm-5.2", "GLM 5.2"),
    ("alitp-intl", "deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("openai-tts-models", "gpt-4o-mini-tts", "GPT-4o Mini TTS"),
    ("openai-tts-models", "tts-1-hd", "TTS-1 HD"),
    ("openai-tts-models", "tts-1", "TTS-1"),
    ("openai-tts-voices", "alloy", "Alloy"),
    ("openai-tts-voices", "ash", "Ash"),
    ("openai-tts-voices", "ballad", "Ballad"),
    ("openai-tts-voices", "cedar", "Cedar"),
    ("openai-tts-voices", "coral", "Coral"),
    ("openai-tts-voices", "echo", "Echo"),
    ("openai-tts-voices", "fable", "Fable"),
    ("openai-tts-voices", "marin", "Marin"),
    ("openai-tts-voices", "nova", "Nova"),
    ("openai-tts-voices", "onyx", "Onyx"),
    ("openai-tts-voices", "sage", "Sage"),
    ("openai-tts-voices", "shimmer", "Shimmer"),
    ("openai-tts-voices", "verse", "Verse"),
    ("openrouter-tts-models", "openai/gpt-4o-mini-tts", "GPT-4o Mini TTS"),
    ("openrouter-tts-models", "openai/tts-1-hd", "TTS-1 HD"),
    ("openrouter-tts-models", "openai/tts-1", "TTS-1"),
    ("openrouter-tts-voices", "alloy", "Alloy"),
    ("openrouter-tts-voices", "ash", "Ash"),
    ("openrouter-tts-voices", "ballad", "Ballad"),
    ("openrouter-tts-voices", "cedar", "Cedar"),
    ("openrouter-tts-voices", "coral", "Coral"),
    ("openrouter-tts-voices", "echo", "Echo"),
    ("openrouter-tts-voices", "fable", "Fable"),
    ("openrouter-tts-voices", "marin", "Marin"),
    ("openrouter-tts-voices", "nova", "Nova"),
    ("openrouter-tts-voices", "onyx", "Onyx"),
    ("openrouter-tts-voices", "sage", "Sage"),
    ("openrouter-tts-voices", "shimmer", "Shimmer"),
    ("openrouter-tts-voices", "verse", "Verse"),
    ("elevenlabs-tts-models", "eleven_flash_v2_5", "Flash v2.5 (Fastest)"),
    ("elevenlabs-tts-models", "eleven_turbo_v2_5", "Turbo v2.5 (Fast)"),
    ("elevenlabs-tts-models", "eleven_multilingual_v2", "Multilingual v2 (Quality)"),
    ("elevenlabs-tts-models", "eleven_monolingual_v1", "Monolingual v1 (English)"),
    ("edge-tts", "en-US-AriaNeural", "Aria (en-US)"),
    ("edge-tts", "en-US-GuyNeural", "Guy (en-US)"),
    ("edge-tts", "en-GB-SoniaNeural", "Sonia (en-GB)"),
    ("edge-tts", "vi-VN-HoaiMyNeural", "Hoai My (vi-VN)"),
    ("edge-tts", "vi-VN-NamMinhNeural", "Nam Minh (vi-VN)"),
    ("edge-tts", "zh-CN-XiaoxiaoNeural", "Xiaoxiao (zh-CN)"),
    ("edge-tts", "zh-CN-YunxiNeural", "Yunxi (zh-CN)"),
    ("edge-tts", "fr-FR-DeniseNeural", "Denise (fr-FR)"),
    ("edge-tts", "de-DE-KatjaNeural", "Katja (de-DE)"),
    ("edge-tts", "ja-JP-NanamiNeural", "Nanami (ja-JP)"),
    ("edge-tts", "ko-KR-SunHiNeural", "SunHi (ko-KR)"),
    ("local-device", "default", "System Default Voice"),
    ("google-tts", "af", "Afrikaans"),
    ("google-tts", "ar", "Arabic"),
    ("google-tts", "bg", "Bulgarian"),
    ("google-tts", "bn", "Bengali"),
    ("google-tts", "bs", "Bosnian"),
    ("google-tts", "ca", "Catalan"),
    ("google-tts", "cs", "Czech"),
    ("google-tts", "cy", "Welsh"),
    ("google-tts", "da", "Danish"),
    ("google-tts", "de", "German"),
    ("google-tts", "el", "Greek"),
    ("google-tts", "en", "English"),
    ("google-tts", "eo", "Esperanto"),
    ("google-tts", "es", "Spanish"),
    ("google-tts", "et", "Estonian"),
    ("google-tts", "fi", "Finnish"),
    ("google-tts", "fr", "French"),
    ("google-tts", "gu", "Gujarati"),
    ("google-tts", "hi", "Hindi"),
    ("google-tts", "hr", "Croatian"),
    ("google-tts", "hu", "Hungarian"),
    ("google-tts", "hy", "Armenian"),
    ("google-tts", "id", "Indonesian"),
    ("google-tts", "is", "Icelandic"),
    ("google-tts", "it", "Italian"),
    ("google-tts", "ja", "Japanese"),
    ("google-tts", "jw", "Javanese"),
    ("google-tts", "km", "Khmer"),
    ("google-tts", "kn", "Kannada"),
    ("google-tts", "ko", "Korean"),
    ("google-tts", "la", "Latin"),
    ("google-tts", "lv", "Latvian"),
    ("google-tts", "mk", "Macedonian"),
    ("google-tts", "ml", "Malayalam"),
    ("google-tts", "mr", "Marathi"),
    ("google-tts", "my", "Myanmar (Burmese)"),
    ("google-tts", "ne", "Nepali"),
    ("google-tts", "nl", "Dutch"),
    ("google-tts", "no", "Norwegian"),
    ("google-tts", "pl", "Polish"),
    ("google-tts", "pt", "Portuguese"),
    ("google-tts", "ro", "Romanian"),
    ("google-tts", "ru", "Russian"),
    ("google-tts", "si", "Sinhala"),
    ("google-tts", "sk", "Slovak"),
    ("google-tts", "sq", "Albanian"),
    ("google-tts", "sr", "Serbian"),
    ("google-tts", "su", "Sundanese"),
    ("google-tts", "sv", "Swedish"),
    ("google-tts", "sw", "Swahili"),
    ("google-tts", "ta", "Tamil"),
    ("google-tts", "te", "Telugu"),
    ("google-tts", "th", "Thai"),
    ("google-tts", "tl", "Filipino"),
    ("google-tts", "tr", "Turkish"),
    ("google-tts", "uk", "Ukrainian"),
    ("google-tts", "ur", "Urdu"),
    ("google-tts", "vi", "Vietnamese"),
    ("google-tts", "zh-CN", "Chinese (Simplified)"),
    ("google-tts", "zh-TW", "Chinese (Traditional)"),
    ("gemini-tts-models", "gemini-3.1-flash-tts-preview", "Gemini 3.1 Flash TTS"),
    ("gemini-tts-models", "gemini-2.5-flash-preview-tts", "Gemini 2.5 Flash TTS"),
    ("gemini-tts-models", "gemini-2.5-pro-preview-tts", "Gemini 2.5 Pro TTS"),
    ("gemini-tts-voices", "Zephyr", "Zephyr"),
    ("gemini-tts-voices", "Puck", "Puck"),
    ("gemini-tts-voices", "Charon", "Charon"),
    ("gemini-tts-voices", "Kore", "Kore"),
    ("gemini-tts-voices", "Fenrir", "Fenrir"),
    ("gemini-tts-voices", "Leda", "Leda"),
    ("gemini-tts-voices", "Orus", "Orus"),
    ("gemini-tts-voices", "Aoede", "Aoede"),
    ("gemini-tts-voices", "Callirrhoe", "Callirrhoe"),
    ("gemini-tts-voices", "Autonoe", "Autonoe"),
    ("gemini-tts-voices", "Enceladus", "Enceladus"),
    ("gemini-tts-voices", "Iapetus", "Iapetus"),
    ("gemini-tts-voices", "Umbriel", "Umbriel"),
    ("gemini-tts-voices", "Algieba", "Algieba"),
    ("gemini-tts-voices", "Despina", "Despina"),
    ("gemini-tts-voices", "Erinome", "Erinome"),
    ("gemini-tts-voices", "Algenib", "Algenib"),
    ("gemini-tts-voices", "Rasalgethi", "Rasalgethi"),
    ("gemini-tts-voices", "Laomedeia", "Laomedeia"),
    ("gemini-tts-voices", "Achernar", "Achernar"),
    ("gemini-tts-voices", "Alnilam", "Alnilam"),
    ("gemini-tts-voices", "Schedar", "Schedar"),
    ("gemini-tts-voices", "Gacrux", "Gacrux"),
    ("gemini-tts-voices", "Pulcherrima", "Pulcherrima"),
    ("gemini-tts-voices", "Achird", "Achird"),
    ("gemini-tts-voices", "Zubenelgenubi", "Zubenelgenubi"),
    ("gemini-tts-voices", "Vindemiatrix", "Vindemiatrix"),
    ("gemini-tts-voices", "Sadachbia", "Sadachbia"),
    ("gemini-tts-voices", "Sadaltager", "Sadaltager"),
    ("gemini-tts-voices", "Sulafat", "Sulafat"),
    ("xiaomi-mimo-tts-models", "mimo-v2.5-tts", "MiMo V2.5 TTS"),
    // total: 914 entries
];

// Capabilities (Caps struct + get_capabilities_for_model) are now sourced from
// the Phase 3 registry's capabilities module, which implements the full 4-step
// fallback chain (provider-specific overrides -> canonical exact -> pattern -> default).
// Re-export so existing `use crate::providers::capabilities::{self, AI_MODELS}` +
// `capabilities::get_capabilities_for_model(...)` call sites resolve to the registry fn.
pub use crate::providers::registry::capabilities::{Caps, get_capabilities_for_model};
