//! Cursor executor.
//! Port of open-sse/executors/cursor.js.
//!
//! Routes chat completions through Cursor's Connect-RPC streaming endpoint
//! (https://api2.cursor.sh/aiserver.v1.ChatService/StreamUnifiedChatWithTools).
//!
//! Auth: Cursor access token from connection.data (apiKey / token field).
//! Machine ID from connection.data.machineId. Ghost mode from data.ghostMode
//! (defaults to true). Headers built by cursor_checksum::build_cursor_headers.
//!
//! Wire protocol: Connect-RPC over HTTPS (Content-Type: application/connect+proto).
//! Request: protobuf body generated by cursor_proto::generate_cursor_body.
//! Response: Connect-RPC framed bytes (possibly gzip-compressed), parsed by
//! cursor_proto::parse_connect_rpc_frame and cursor_proto::extract_text_from_response,
//! re-emitted as OpenAI-compatible SSE.
//!
//! Tool results are sent as a separate Connect-RPC frame via
//! cursor_proto::generate_tool_result_body.
//!
//! NOTE: depends on cursor_proto D1 verification status.

use std::collections::HashMap;
use std::io::Read;

use async_trait::async_trait;
use axum::http::{HeaderMap, StatusCode};
use bytes::Bytes;
use futures::{Stream, StreamExt};
use serde_json::{json, Value};

use super::base::{build_client, get_connection_auth, ProviderExecutor, UpstreamResponse};
use crate::db::repos::connections::ProviderConnection;
use crate::proxy::executors::{cursor_checksum, cursor_proto};
// The response adapter for cursor→openai is a passthrough (the executor already
// produces OpenAI-format SSE/JSON from the binary Connect-RPC frames), so we
// do not need to call select_response_adapter at runtime.

/// Cursor Connect-RPC streaming endpoint.
const CURSOR_CHAT_URL: &str =
    "https://api2.cursor.sh/aiserver.v1.ChatService/StreamUnifiedChatWithTools";

/// Connect-RPC compression flags (matching cursor.js COMPRESS_FLAG).
const COMPRESS_NONE: u8 = 0x00;
const COMPRESS_GZIP: u8 = 0x01;
const COMPRESS_TRAILER: u8 = 0x02;
const COMPRESS_GZIP_TRAILER: u8 = 0x03;

pub struct CursorExecutor;

fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

fn now_secs() -> u64 {
    now_ms() / 1000
}

/// Resolve an OpenAI model name to a Cursor internal model string.
///
/// Most Cursor models are passed as-is (e.g. "claude-4.5-sonnet", "gpt-5.2-codex").
/// The "default" model maps to Cursor's auto-select. This function strips any
/// provider prefix (e.g. "cursor/claude-4.5-sonnet" → "claude-4.5-sonnet")
/// and handles known alias mappings.
pub fn resolve_cursor_model(openai_model: &str) -> String {
    // Strip provider prefix if present (e.g. "cursor/gpt-5.2" → "gpt-5.2")
    let model = if let Some(slash_pos) = openai_model.find('/') {
        &openai_model[slash_pos + 1..]
    } else {
        openai_model
    };

    // Known model aliases — Cursor accepts these IDs as-is from the registry.
    // "default" maps to Cursor's auto-select.
    // Add any alias mappings here as needed.
    model.to_string()
}

/// Check if a model is a Composer model (for thinking-content extraction).
fn is_composer_model(model: &str) -> bool {
    let model_id = model.rsplit('/').next().unwrap_or(model);
    model_id.starts_with("composer")
}

/// Extract visible composer content from thinking blocks.
///
/// Cursor's Composer models wrap their visible output inside <think>...
/// tags. This function extracts content after the last  tag.
fn visible_composer_content_from_thinking(thinking: &str) -> String {
    if thinking.is_empty() {
        return String::new();
    }
    let end_tag = "";
    if let Some(end_idx) = thinking.rfind(end_tag) {
        thinking[end_idx + end_tag.len()..].trim_start().to_string()
    } else {
        String::new()
    }
}

/// Decompress a Connect-RPC payload based on its flags byte.
/// Returns the decompressed bytes, or the original payload if decompression fails.
///
/// Mirrors cursor.js `decompressPayload`: JSON error frames (starting with `{"`)
/// are returned as-is; gzip-compressed frames are decompressed with a cascade
/// of gzip → zlib inflate → raw deflate fallbacks.
fn decompress_payload(payload: &[u8], flags: u8) -> Vec<u8> {
    // Skip decompression for JSON error frames (starts with `{"`)
    let is_json = payload.len() > 10
        && payload[0] == 0x7b  // '{'
        && payload[1] == 0x22; // '"'

    if is_json {
        return payload.to_vec();
    }

    if flags == COMPRESS_GZIP || flags == COMPRESS_TRAILER || flags == COMPRESS_GZIP_TRAILER {
        // Primary: try gzip decompression
        let mut decoder = flate2::read::GzDecoder::new(payload);
        let mut out = Vec::new();
        if decoder.read_to_end(&mut out).is_ok() {
            return out;
        }
        // Fallback: try zlib inflate
        let mut decoder = flate2::read::ZlibDecoder::new(payload);
        let mut out = Vec::new();
        if decoder.read_to_end(&mut out).is_ok() {
            return out;
        }
        // Last resort: try raw deflate
        let mut decoder = flate2::read::DeflateDecoder::new(payload);
        let mut out = Vec::new();
        if decoder.read_to_end(&mut out).is_ok() {
            return out;
        }
    }

    payload.to_vec()
}

/// Check if the request body is a pure text conversation (no tool calls or tool results).
/// If so, the AgentService path could be used. For now, we keep everything on the
/// ChatService path for stability.
#[allow(dead_code)]
fn is_agent_text_request(body: &Value) -> bool {
    let messages = match body.get("messages").and_then(|v| v.as_array()) {
        Some(m) => m,
        None => return false,
    };
    messages.iter().all(|msg| {
        // If any message has tool_calls or is a tool result, not agent text
        if msg
            .get("tool_calls")
            .and_then(|v| v.as_array())
            .map(|a| !a.is_empty())
            .unwrap_or(false)
        {
            return false;
        }
        if msg.get("role").and_then(|v| v.as_str()) == Some("tool") {
            return false;
        }
        // Content must be string or array of text parts
        match msg.get("content") {
            Some(Value::String(_)) => true,
            Some(Value::Array(parts)) => parts
                .iter()
                .all(|p| p.get("type").and_then(|v| v.as_str()) == Some("text")),
            _ => false,
        }
    })
}

/// Extract text from message content (string or array of text parts).
fn text_from_content(content: &Value) -> String {
    if let Some(s) = content.as_str() {
        return s.to_string();
    }
    if let Some(arr) = content.as_array() {
        let parts: Vec<String> = arr
            .iter()
            .filter(|p| p.get("type").and_then(|v| v.as_str()) == Some("text"))
            .filter_map(|p| {
                p.get("text")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string())
            })
            .collect();
        return parts.join("\n");
    }
    String::new()
}

/// Detect if any messages contain tool results that need a separate frame.
fn has_tool_results(body: &Value) -> bool {
    let messages = match body.get("messages").and_then(|v| v.as_array()) {
        Some(m) => m,
        None => return false,
    };
    messages.iter().any(|msg| {
        msg.get("role").and_then(|v| v.as_str()) == Some("tool")
            || msg
                .get("content")
                .and_then(|v| v.as_array())
                .map(|arr| {
                    arr.iter()
                        .any(|p| p.get("type").and_then(|v| v.as_str()) == Some("tool_result"))
                })
                .unwrap_or(false)
    })
}

/// Build a JSON error response body in OpenAI format.
fn error_json(message: &str, error_type: &str, code: &str) -> String {
    json!({
        "error": {
            "message": message,
            "type": error_type,
            "code": code
        }
    })
    .to_string()
}

/// Build an OpenAI chat.completion.chunk SSE frame.
fn chat_chunk_sse(
    id: &str,
    created: u64,
    model: &str,
    delta: Value,
    finish_reason: Option<&str>,
) -> String {
    let chunk = json!({
        "id": id,
        "object": "chat.completion.chunk",
        "created": created,
        "model": model,
        "choices": [{
            "index": 0,
            "delta": delta,
            "finish_reason": finish_reason
        }]
    });
    format!("data: {}\n\n", chunk)
}

/// Build Cursor connection credentials from conn.data.
struct CursorCredentials {
    access_token: String,
    machine_id: Option<String>,
    ghost_mode: bool,
}

/// Extract Cursor credentials from the connection data JSON.
/// Cursor tokens are stored as the access token; machineId may be stored or generated.
fn extract_credentials(conn: &ProviderConnection) -> Result<CursorCredentials, UpstreamResponse> {
    let access_token = get_connection_auth(&conn.data).ok_or_else(|| UpstreamResponse::Error {
        status: StatusCode::UNAUTHORIZED,
        message: "cursor auth failed".to_string(),
    })?;

    let machine_id = conn
        .data
        .get("machineId")
        .or_else(|| conn.data.get("machine_id"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string());

    let ghost_mode = conn
        .data
        .get("ghostMode")
        .or_else(|| conn.data.get("ghost_mode"))
        .and_then(|v| v.as_bool())
        .unwrap_or(true); // default to true (ghost mode on)

    Ok(CursorCredentials {
        access_token,
        machine_id,
        ghost_mode,
    })
}

/// Determine if we should force agent mode based on User-Agent.
fn should_force_agent_mode(headers: &HeaderMap) -> bool {
    if let Some(ua) = headers.get("user-agent").and_then(|v| v.to_str().ok()) {
        ua.contains("claude-cli") || ua.contains("claude-code") || ua.contains("Claude Code")
    } else {
        false
    }
}

/// Get reasoning effort from the request body.
fn get_reasoning_effort(body: &Value) -> Option<String> {
    body.get("reasoning_effort")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
}

/// Parse a JSON error frame from a Connect-RPC payload.
/// Returns Some(error_json_string) if the payload is a JSON error.
fn try_parse_json_error(payload: &[u8]) -> Option<String> {
    if payload.is_empty() || payload[0] != 0x7b {
        return None;
    }
    let text = String::from_utf8(payload.to_vec()).ok()?;
    if !text.contains("\"error\"") {
        return None;
    }
    let parsed: Value = serde_json::from_str(&text).ok()?;
    let error = parsed.get("error")?;
    // Extract error message from Cursor's error format
    let msg = error
        .get("details")
        .and_then(|d| d.as_array())
        .and_then(|arr| arr.first())
        .and_then(|d| d.get("debug"))
        .and_then(|d| d.get("details"))
        .and_then(|d| d.get("title"))
        .and_then(|v| v.as_str())
        .or_else(|| {
            error
                .get("details")
                .and_then(|d| d.as_array())
                .and_then(|arr| arr.first())
                .and_then(|d| d.get("debug"))
                .and_then(|d| d.get("details"))
                .and_then(|d| d.get("detail"))
                .and_then(|v| v.as_str())
        })
        .or_else(|| error.get("message").and_then(|v| v.as_str()))
        .unwrap_or("API Error");

    let is_rate_limit = error
        .get("code")
        .and_then(|v| v.as_str())
        .map(|s| s == "resource_exhausted")
        .unwrap_or(false);

    let error_code = error
        .get("details")
        .and_then(|d| d.as_array())
        .and_then(|arr| arr.first())
        .and_then(|d| d.get("debug"))
        .and_then(|d| d.get("error"))
        .and_then(|v| v.as_str())
        .unwrap_or("unknown");

    let error_type = if is_rate_limit {
        "rate_limit_error"
    } else {
        "api_error"
    };

    Some(
        json!({
            "error": {
                "message": msg,
                "type": error_type,
                "code": error_code
            }
        })
        .to_string(),
    )
}

/// Track streaming tool calls by ID for accumulation.
#[derive(Clone)]
struct StreamingToolCall {
    id: String,
    name: String,
    arguments: String,
    is_last: bool,
    index: usize,
}

/// Process a full Cursor response buffer (non-streaming) and build an OpenAI JSON response.
///
/// Parses all Connect-RPC frames, accumulates text/thinking/tool_calls,
/// and returns a complete chat.completion JSON object.
fn build_complete_response(buffer: &[u8], model: &str, request_body: &Value) -> String {
    let response_id = format!("chatcmpl-cursor-{}", now_ms());
    let created = now_secs();

    let mut offset = 0usize;
    let mut total_content = String::new();
    let mut total_thinking = String::new();
    let mut tool_calls_map: HashMap<String, StreamingToolCall> = HashMap::new();
    let mut finalized_tool_calls: Vec<Value> = Vec::new();
    let mut finalized_ids: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut frame_count = 0u32;

    tracing::debug!(
        "[CURSOR COMPLETE] Buffer length: {} bytes, model: {}",
        buffer.len(),
        model
    );

    while offset < buffer.len() {
        // Parse a Connect-RPC frame
        let (flags, payload, consumed) =
            match cursor_proto::parse_connect_rpc_frame(&buffer[offset..]) {
                Some(f) => f,
                None => break,
            };
        offset += consumed;
        frame_count += 1;

        // Decompress the payload if needed
        let decompressed = decompress_payload(&payload, flags);

        // Check for JSON error frames
        if !decompressed.is_empty() && decompressed[0] == 0x7b {
            if let Some(error_json) = try_parse_json_error(&decompressed) {
                let has_content = !total_content.is_empty() || !tool_calls_map.is_empty();
                if has_content {
                    break;
                }
                return error_json;
            }
        }

        // Skip trailer frames (they carry metadata, not content)
        if flags & COMPRESS_TRAILER != 0 {
            continue;
        }

        // Extract text/thinking/tool_call from the protobuf payload
        let result = cursor_proto::extract_text_from_response(&decompressed);

        if let Some(err) = result.error {
            let has_content = !total_content.is_empty() || !tool_calls_map.is_empty();
            if has_content {
                break;
            }
            return json!({
                "error": {
                    "message": err,
                    "type": "rate_limit_error",
                    "code": "rate_limited"
                }
            })
            .to_string();
        }

        // Handle tool calls
        if let Some(tc) = result.tool_call {
            if tool_calls_map.contains_key(&tc.id) {
                let existing = tool_calls_map.get_mut(&tc.id).unwrap();
                existing.arguments.push_str(&tc.arguments);
                existing.is_last = tc.is_last;
            } else {
                let idx = tool_calls_map.len();
                tool_calls_map.insert(
                    tc.id.clone(),
                    StreamingToolCall {
                        id: tc.id.clone(),
                        name: tc.name.clone(),
                        arguments: tc.arguments.clone(),
                        is_last: tc.is_last,
                        index: idx,
                    },
                );
            }

            if tc.is_last {
                if let Some(final_tc) = tool_calls_map.get(&tc.id) {
                    if !finalized_ids.contains(&tc.id) {
                        finalized_ids.insert(tc.id.clone());
                        finalized_tool_calls.push(json!({
                            "id": final_tc.id,
                            "type": "function",
                            "function": {
                                "name": final_tc.name,
                                "arguments": final_tc.arguments
                            }
                        }));
                    }
                }
            }
        }

        // Accumulate text
        if let Some(ref text) = result.text {
            total_content.push_str(text);
        }

        // Accumulate thinking
        if let Some(ref thinking) = result.thinking {
            total_thinking.push_str(thinking);
        }
    }

    tracing::debug!(
        "[CURSOR COMPLETE] Parsed {} frames, tool_calls: {}",
        frame_count,
        finalized_tool_calls.len()
    );

    // Finalize any remaining tool calls (stream may have ended without isLast=true)
    for (id, tc) in &tool_calls_map {
        if !finalized_ids.contains(id) {
            tracing::debug!(
                "[CURSOR COMPLETE] Finalizing incomplete tool call: {}, isLast={}",
                id,
                tc.is_last
            );
            finalized_tool_calls.push(json!({
                "id": tc.id,
                "type": "function",
                "function": {
                    "name": tc.name,
                    "arguments": tc.arguments
                }
            }));
        }
    }

    // Handle Composer model thinking extraction
    let final_content = if is_composer_model(model) {
        let visible = visible_composer_content_from_thinking(&total_thinking);
        if !visible.is_empty() {
            visible
        } else {
            total_content
        }
    } else {
        total_content
    };

    // Build the message
    let mut message = json!({
        "role": "assistant",
        "content": if final_content.is_empty() { Value::Null } else { json!(final_content) }
    });

    if !finalized_tool_calls.is_empty() {
        message["tool_calls"] = json!(finalized_tool_calls);
    }

    // Estimate usage (simple character-based estimate)
    let content_len = final_content.len();
    let prompt_tokens = estimate_prompt_tokens(request_body);
    let completion_tokens = ((content_len + 3) / 4) as u64; // rough estimate
    let total_tokens = prompt_tokens + completion_tokens;

    let finish_reason = if !finalized_tool_calls.is_empty() {
        "tool_calls"
    } else {
        "stop"
    };

    json!({
        "id": response_id,
        "object": "chat.completion",
        "created": created,
        "model": model,
        "choices": [{
            "index": 0,
            "message": message,
            "finish_reason": finish_reason
        }],
        "usage": {
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens
        }
    })
    .to_string()
}

/// Estimate prompt tokens from the request body (rough: 4 chars per token).
fn estimate_prompt_tokens(body: &Value) -> u64 {
    let messages = body.get("messages").and_then(|v| v.as_array());
    let mut total = 0u64;
    if let Some(msgs) = messages {
        for msg in msgs {
            let content = text_from_content(msg.get("content").unwrap_or(&Value::Null));
            total += (content.len() as u64 + 3) / 4;
        }
    }
    total.max(1)
}

/// Wrap the Cursor binary response into an OpenAI-compatible SSE stream.
///
/// Reads the upstream HTTP body, parses Connect-RPC frames, extracts
/// text/thinking/tool_calls, and re-emits as OpenAI SSE chunks.
fn wrap_cursor_stream(
    upstream: impl Stream<Item = Result<Bytes, reqwest::Error>> + Send + Unpin + 'static,
    model: String,
) -> Box<dyn Stream<Item = Result<Bytes, std::io::Error>> + Send + Unpin> {
    use tokio::sync::mpsc;
    use tokio_stream::wrappers::ReceiverStream;

    let (tx, rx) = mpsc::channel::<Result<Bytes, std::io::Error>>(64);

    tokio::spawn(async move {
        let mut upstream = Box::pin(upstream);
        let response_id = format!("chatcmpl-cursor-{}", now_ms());
        let created = now_secs();
        let mut role_emitted = false;
        let mut total_content = String::new();
        let mut total_thinking = String::new();
        let mut emitted_composer_thinking_len: usize = 0;
        let mut tool_calls_map: HashMap<String, StreamingToolCall> = HashMap::new();
        let mut finalized_ids: std::collections::HashSet<String> = std::collections::HashSet::new();
        let mut emitted_tool_call_ids: std::collections::HashSet<String> =
            std::collections::HashSet::new();
        let mut tool_call_count: usize = 0;
        let mut pending: Vec<u8> = Vec::new();
        let mut had_error: Option<String> = None;
        let mut done = false;

        while !done {
            match upstream.next().await {
                Some(Ok(chunk)) => {
                    pending.extend_from_slice(&chunk);
                }
                Some(Err(e)) => {
                    let _ = tx
                        .send(Err(std::io::Error::new(std::io::ErrorKind::Other, e)))
                        .await;
                    return;
                }
                None => break,
            }

            // Drain all complete frames from pending
            loop {
                if done {
                    break;
                }
                let (flags, payload, consumed) =
                    match cursor_proto::parse_connect_rpc_frame(&pending) {
                        Some(f) => f,
                        None => break,
                    };

                // Remove consumed frame from pending
                pending.drain(..consumed);

                // Decompress payload
                let decompressed = decompress_payload(&payload, flags);

                // Check for JSON error frames
                if !decompressed.is_empty() && decompressed[0] == 0x7b {
                    if let Some(error_json_str) = try_parse_json_error(&decompressed) {
                        let has_content = !total_content.is_empty() || !tool_calls_map.is_empty();
                        if has_content {
                            done = true;
                            break;
                        }
                        // Emit error as SSE
                        let error_chunk = format!("data: {}\n\n", error_json_str);
                        let _ = tx.send(Ok(Bytes::from(error_chunk))).await;
                        let _ = tx.send(Ok(Bytes::from("data: [DONE]\n\n"))).await;
                        return;
                    }
                }

                // Skip trailer frames
                if flags & COMPRESS_TRAILER != 0 {
                    continue;
                }

                // Extract content from protobuf payload
                let result = cursor_proto::extract_text_from_response(&decompressed);

                if let Some(err) = result.error {
                    let has_content = !total_content.is_empty() || !tool_calls_map.is_empty();
                    if has_content {
                        done = true;
                        break;
                    }
                    had_error = Some(err);
                    done = true;
                    break;
                }

                // Handle tool calls
                if let Some(tc) = result.tool_call {
                    if !role_emitted {
                        let role_chunk = chat_chunk_sse(
                            &response_id,
                            created,
                            &model,
                            json!({"role": "assistant", "content": ""}),
                            None,
                        );
                        let _ = tx.send(Ok(Bytes::from(role_chunk))).await;
                        role_emitted = true;
                    }

                    if tool_calls_map.contains_key(&tc.id) {
                        let existing = tool_calls_map.get_mut(&tc.id).unwrap();
                        existing.arguments.push_str(&tc.arguments);
                        existing.is_last = tc.is_last;

                        // Stream the delta arguments
                        if !tc.arguments.is_empty() {
                            emitted_tool_call_ids.insert(tc.id.clone());
                            let tc_chunk = chat_chunk_sse(
                                &response_id,
                                created,
                                &model,
                                json!({
                                    "tool_calls": [{
                                        "index": existing.index,
                                        "id": tc.id,
                                        "type": "function",
                                        "function": {
                                            "name": existing.name,
                                            "arguments": existing.arguments
                                        }
                                    }]
                                }),
                                None,
                            );
                            let _ = tx.send(Ok(Bytes::from(tc_chunk))).await;
                        }
                    } else {
                        // New tool call
                        let idx = tool_call_count;
                        tool_call_count += 1;
                        finalized_ids.insert(tc.id.clone());
                        tool_calls_map.insert(
                            tc.id.clone(),
                            StreamingToolCall {
                                id: tc.id.clone(),
                                name: tc.name.clone(),
                                arguments: tc.arguments.clone(),
                                is_last: tc.is_last,
                                index: idx,
                            },
                        );

                        emitted_tool_call_ids.insert(tc.id.clone());
                        let tc_chunk = chat_chunk_sse(
                            &response_id,
                            created,
                            &model,
                            json!({
                                "tool_calls": [{
                                    "index": idx,
                                    "id": tc.id,
                                    "type": "function",
                                    "function": {
                                        "name": tc.name,
                                        "arguments": tc.arguments
                                    }
                                }]
                            }),
                            None,
                        );
                        let _ = tx.send(Ok(Bytes::from(tc_chunk))).await;
                    }
                }

                // Handle text content
                if let Some(ref text) = result.text {
                    if !text.is_empty() {
                        total_content.push_str(text);
                        let delta = if !role_emitted && tool_calls_map.is_empty() {
                            role_emitted = true;
                            json!({"role": "assistant", "content": text})
                        } else {
                            json!({"content": text})
                        };
                        let chunk = chat_chunk_sse(&response_id, created, &model, delta, None);
                        let _ = tx.send(Ok(Bytes::from(chunk))).await;
                    }
                }

                // Handle Composer thinking content
                if is_composer_model(&model) {
                    if let Some(ref thinking) = result.thinking {
                        total_thinking.push_str(thinking);
                        let visible = visible_composer_content_from_thinking(&total_thinking);
                        if visible.len() > emitted_composer_thinking_len {
                            let delta_content = &visible[emitted_composer_thinking_len..];
                            emitted_composer_thinking_len = visible.len();
                            total_content.push_str(delta_content);
                            let delta = if !role_emitted && tool_calls_map.is_empty() {
                                role_emitted = true;
                                json!({"role": "assistant", "content": delta_content})
                            } else {
                                json!({"content": delta_content})
                            };
                            let chunk = chat_chunk_sse(&response_id, created, &model, delta, None);
                            let _ = tx.send(Ok(Bytes::from(chunk))).await;
                        }
                    }
                }
            }
        }

        // Emit error if any
        if let Some(err_msg) = had_error {
            let error_chunk = format!(
                "data: {}\n\n",
                json!({
                    "error": {"message": err_msg, "type": "api_error"}
                })
            );
            let _ = tx.send(Ok(Bytes::from(error_chunk))).await;
            let _ = tx.send(Ok(Bytes::from("data: [DONE]\n\n"))).await;
            return;
        }

        // Finalize any remaining incomplete tool calls
        for (id, tc) in &tool_calls_map {
            if !finalized_ids.contains(id) {
                let idx = tool_call_count;
                tool_call_count += 1;
                let tc_chunk = chat_chunk_sse(
                    &response_id,
                    created,
                    &model,
                    json!({
                        "tool_calls": [{
                            "index": idx,
                            "id": tc.id,
                            "type": "function",
                            "function": {
                                "name": tc.name,
                                "arguments": tc.arguments
                            }
                        }]
                    }),
                    None,
                );
                if !emitted_tool_call_ids.contains(id) {
                    let _ = tx.send(Ok(Bytes::from(tc_chunk))).await;
                }
            }
        }

        // Emit initial role chunk if nothing was emitted yet
        if !role_emitted && tool_calls_map.is_empty() {
            let role_chunk = chat_chunk_sse(
                &response_id,
                created,
                &model,
                json!({"role": "assistant", "content": ""}),
                None,
            );
            let _ = tx.send(Ok(Bytes::from(role_chunk))).await;
        }

        // Emit finish chunk
        let finish_reason = if !tool_calls_map.is_empty() {
            "tool_calls"
        } else {
            "stop"
        };

        let prompt_tokens = 0u64; // Would need request body for accurate estimate
        let completion_tokens = (total_content.len() as u64 + 3) / 4;

        let mut finish_payload = json!({
            "id": response_id,
            "object": "chat.completion.chunk",
            "created": created,
            "model": model,
            "choices": [{
                "index": 0,
                "delta": {},
                "finish_reason": finish_reason
            }]
        });
        if prompt_tokens > 0 || completion_tokens > 0 {
            finish_payload["usage"] = json!({
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": prompt_tokens + completion_tokens
            });
        }

        let _ = tx
            .send(Ok(Bytes::from(format!("data: {}\n\n", finish_payload))))
            .await;
        let _ = tx.send(Ok(Bytes::from("data: [DONE]\n\n"))).await;
    });

    Box::new(ReceiverStream::new(rx))
}

#[async_trait]
impl ProviderExecutor for CursorExecutor {
    async fn stream(
        &self,
        conn: &ProviderConnection,
        body: Value,
        headers: HeaderMap,
    ) -> anyhow::Result<UpstreamResponse> {
        self.execute(conn, body, headers, true).await
    }

    async fn complete(
        &self,
        conn: &ProviderConnection,
        body: Value,
        headers: HeaderMap,
    ) -> anyhow::Result<UpstreamResponse> {
        self.execute(conn, body, headers, false).await
    }
}

impl CursorExecutor {
    async fn execute(
        &self,
        conn: &ProviderConnection,
        body: Value,
        headers: HeaderMap,
        stream: bool,
    ) -> anyhow::Result<UpstreamResponse> {
        // Extract credentials
        let creds = match extract_credentials(conn) {
            Ok(c) => c,
            Err(resp) => return Ok(resp),
        };

        // Get model from body, resolve to Cursor model
        let openai_model = body
            .get("model")
            .and_then(|v| v.as_str())
            .unwrap_or("default")
            .to_string();
        let cursor_model = resolve_cursor_model(&openai_model);

        // Extract messages and tools
        let messages: Vec<Value> = body
            .get("messages")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();
        let _tools: Vec<Value> = body
            .get("tools")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();

        // Get reasoning effort
        let reasoning_effort = get_reasoning_effort(&body);

        // Detect force agent mode from User-Agent
        let force_agent_mode = should_force_agent_mode(&headers);

        // Build the request body via cursor_proto
        let request_body = cursor_proto::generate_cursor_body(
            &messages,
            &cursor_model,
            &_tools,
            reasoning_effort.as_deref(),
            force_agent_mode,
        );

        // Build headers via cursor_checksum
        let mut cursor_headers: Vec<(String, String)> = cursor_checksum::build_cursor_headers(
            &creds.access_token,
            creds.machine_id.as_deref(),
            creds.ghost_mode,
        );

        // Add Cursor transport headers from the registry config
        cursor_headers.push(("connect-accept-encoding".to_string(), "gzip".to_string()));
        cursor_headers.push(("connect-protocol-version".to_string(), "1".to_string()));
        cursor_headers.push((
            "Content-Type".to_string(),
            "application/connect+proto".to_string(),
        ));
        cursor_headers.push(("User-Agent".to_string(), "connect-es/1.6.1".to_string()));

        // Build HTTP client and send request
        let client = build_client();
        let mut req_builder = client.post(CURSOR_CHAT_URL).body(request_body);

        for (key, value) in &cursor_headers {
            req_builder = req_builder.header(key.as_str(), value.as_str());
        }

        // Check for tool results that need a separate frame
        // TODO Phase4: Cursor sends tool results as a separate Connect-RPC frame.
        // The generate_tool_result_body function creates this frame. For now,
        // tool results are handled via the translator (converted to text blocks
        // in the messages), so this path is deferred.
        if has_tool_results(&body) {
            tracing::warn!(
                "[CURSOR] Tool results detected — separate frame handling is TODO Phase4. \
                 Tool results are currently embedded as text blocks via the translator."
            );
            // When cursor_proto::generate_tool_result_body is stable:
            // let tool_result_frame = cursor_proto::generate_tool_result_body(...);
            // Would need to send as a second body part or separate request.
        }

        let resp = req_builder.send().await;

        let resp = match resp {
            Ok(r) => r,
            Err(e) => {
                tracing::warn!("Cursor request failed: {}", e);
                return Ok(UpstreamResponse::Error {
                    status: StatusCode::BAD_GATEWAY,
                    message: format!("cursor connection error: {}", e),
                });
            }
        };

        // Check status code
        let status = resp.status();
        if status == StatusCode::UNAUTHORIZED {
            tracing::warn!("Cursor auth failed (401) for connection {}", conn.id);
            return Ok(UpstreamResponse::Error {
                status: StatusCode::UNAUTHORIZED,
                message: "cursor auth failed".to_string(),
            });
        }

        if !status.is_success() {
            let error_text = resp.text().await.unwrap_or_default();
            // Mask any tokens in the error text
            let masked = mask_tokens(&error_text, &creds.access_token);
            tracing::warn!(
                "Cursor upstream returned {}: {}",
                status,
                &masked[..masked.len().min(200)]
            );
            return Ok(UpstreamResponse::Error {
                status,
                message: format!("[{}]: {}", status.as_u16(), masked),
            });
        }

        if stream {
            // Streaming: wrap the upstream binary stream into OpenAI SSE
            let upstream = resp.bytes_stream();
            let sse_stream = wrap_cursor_stream(upstream, openai_model);

            Ok(UpstreamResponse::Stream {
                headers: HeaderMap::new(),
                stream: sse_stream,
            })
        } else {
            // Non-streaming: buffer the full response, parse frames, build JSON
            let body_bytes = match resp.bytes().await {
                Ok(b) => b,
                Err(e) => {
                    return Ok(UpstreamResponse::Error {
                        status: StatusCode::BAD_GATEWAY,
                        message: format!("cursor read error: {}", e),
                    });
                }
            };

            let json_str = build_complete_response(&body_bytes, &openai_model, &body);
            let json_bytes = Bytes::from(json_str);

            Ok(UpstreamResponse::Json {
                status: StatusCode::OK,
                headers: HeaderMap::new(),
                body: json_bytes,
            })
        }
    }
}

/// Mask any occurrence of the access token in a string with ****.
fn mask_tokens(text: &str, token: &str) -> String {
    if token.is_empty() || token.len() < 8 {
        return text.to_string();
    }
    text.replace(token, "****")
}
