//! Free-tier and free category providers (22 entries).
//! Ported from open-sse/providers/registry/ for category: "freeTier" and "free"

use super::*;

pub static ENTRIES: &[ProviderRegistryEntry] = &[
    // ── freeTier ──
    ProviderRegistryEntry {
        id: "api-airforce",
        priority: 0,
        alias: "af",
        ui_alias: Some("af"),
        display: ProviderDisplay { name: "API.airforce", icon: Some("flight"), color: Some("#0EA5E9"), text_icon: Some("AF"), website: Some("https://api.airforce"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://api.airforce/v1/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "gpt-4o-mini", name: "GPT-4o Mini", kind: None },
            ProviderModel { id: "claude-3.7-sonnet", name: "Claude 3.7 Sonnet", kind: None },
            ProviderModel { id: "deepseek-v3", name: "DeepSeek V3", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "bazaarlink",
        priority: 0,
        alias: "bzl",
        ui_alias: Some("bzl"),
        display: ProviderDisplay { name: "Bazaarlink", icon: Some("storefront"), color: Some("#DC2626"), text_icon: Some("BZ"), website: Some("https://bazaarlink.ai"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://bazaarlink.ai/api/v1/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "auto:free", name: "Auto Free (Zero Cost)", kind: None },
            ProviderModel { id: "claude-opus-4.7", name: "Claude Opus 4.7", kind: None },
            ProviderModel { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", kind: None },
            ProviderModel { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", kind: None },
            ProviderModel { id: "gpt-5.5", name: "GPT-5.5", kind: None },
            ProviderModel { id: "gpt-5.4", name: "GPT-5.4", kind: None },
            ProviderModel { id: "gpt-5.4-mini", name: "GPT-5.4 Mini", kind: None },
            ProviderModel { id: "gpt-5.4-nano", name: "GPT-5.4 Nano", kind: None },
            ProviderModel { id: "grok-4.3", name: "Grok 4.3", kind: None },
            ProviderModel { id: "grok-4.20", name: "Grok 4.20", kind: None },
            ProviderModel { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro", kind: None },
            ProviderModel { id: "gemini-3-flash-preview", name: "Gemini 3 Flash", kind: None },
            ProviderModel { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite", kind: None },
            ProviderModel { id: "kimi-k2.6", name: "Kimi K2.6", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi K2.5", kind: None },
            ProviderModel { id: "glm-5.1", name: "GLM 5.1", kind: None },
            ProviderModel { id: "glm-5", name: "GLM 5", kind: None },
            ProviderModel { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro", kind: None },
            ProviderModel { id: "mimo-v2.5", name: "MiMo-V2.5", kind: None },
            ProviderModel { id: "minimax-m3", name: "MiniMax M3", kind: None },
            ProviderModel { id: "minimax-m2.7", name: "MiniMax M2.7", kind: None },
            ProviderModel { id: "minimax-m2.5", name: "MiniMax M2.5", kind: None },
            ProviderModel { id: "qwen3.6-plus", name: "Qwen 3.6 Plus", kind: None },
            ProviderModel { id: "nemotron-3-super-120b-a12b", name: "Nemotron 3 Super", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "byteplus",
        priority: 70,
        alias: "byteplus",
        ui_alias: Some("bpm"),
        display: ProviderDisplay { name: "BytePlus ModelArk", icon: Some("cloud"), color: Some("#2563EB"), text_icon: Some("BP"), website: Some("https://console.byteplus.com/ark"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://ark.ap-southeast.bytepluses.com/api/coding/v3/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "seed-2-0-pro-260328", name: "Seed 2.0 Pro", kind: None },
            ProviderModel { id: "seed-2-0-code-preview-260328", name: "Seed 2.0 Code Preview", kind: None },
            ProviderModel { id: "seed-2-0-mini-260215", name: "Seed 2.0 Mini", kind: None },
            ProviderModel { id: "seed-2-0-lite-260228", name: "Seed 2.0 Lite", kind: None },
            ProviderModel { id: "kimi-k2-thinking-251104", name: "Kimi K2 Thinking", kind: None },
            ProviderModel { id: "glm-4-7-251222", name: "GLM 4.7", kind: None },
            ProviderModel { id: "gpt-oss-120b-250805", name: "GPT-OSS-120B", kind: None },
        ],
        service_kinds: &["llm"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "cloudflare-ai",
        priority: 60,
        alias: "cloudflare-ai",
        ui_alias: Some("cf"),
        display: ProviderDisplay { name: "Cloudflare", icon: Some("cloud"), color: Some("#F38020"), text_icon: Some("CF"), website: Some("https://developers.cloudflare.com/workers-ai/"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "@cf/meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct", kind: None },
            ProviderModel { id: "@cf/meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct", kind: None },
            ProviderModel { id: "@cf/meta/llama-3.1-8b-instruct-fp8-fast", name: "Llama 3.1 8B Instruct FP8 Fast", kind: None },
            ProviderModel { id: "@cf/meta/llama-3.1-8b-instruct-awq", name: "Llama 3.1 8B Instruct AWQ", kind: None },
            ProviderModel { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24B Instruct", kind: None },
            ProviderModel { id: "@cf/meta/llama-3.1-70b-instruct-fp8-fast", name: "Llama 3.1 70B Instruct FP8 Fast", kind: None },
            ProviderModel { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B Instruct FP8 Fast", kind: None },
            ProviderModel { id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B", kind: None },
            ProviderModel { id: "@cf/moonshotai/kimi-k2.5", name: "Kimi K2.5", kind: None },
            ProviderModel { id: "@cf/moonshotai/kimi-k2.6", name: "Kimi K2.6", kind: None },
            ProviderModel { id: "@cf/zai-org/glm-4.7-flash", name: "GLM 4.7 Flash", kind: None },
            ProviderModel { id: "@cf/qwen/qwq-32b", name: "QwQ 32B", kind: None },
            ProviderModel { id: "@cf/qwen/qwen2.5-coder-32b-instruct", name: "Qwen 2.5 Coder 32B Instruct", kind: None },
            ProviderModel { id: "@cf/black-forest-labs/flux-2-klein-9b", name: "FLUX.2 Klein 9B", kind: None },
            ProviderModel { id: "@cf/black-forest-labs/flux-2-klein-4b", name: "FLUX.2 Klein 4B", kind: None },
            ProviderModel { id: "@cf/black-forest-labs/flux-2-dev", name: "FLUX.2 Dev", kind: None },
            ProviderModel { id: "@cf/leonardo/lucid-origin", name: "Lucid Origin", kind: None },
            ProviderModel { id: "@cf/leonardo/phoenix-1.0", name: "Phoenix 1.0", kind: None },
            ProviderModel { id: "@cf/black-forest-labs/flux-1-schnell", name: "FLUX.1 Schnell", kind: None },
            ProviderModel { id: "@cf/bytedance/stable-diffusion-xl-lightning", name: "SDXL Lightning", kind: None },
            ProviderModel { id: "@cf/lykon/dreamshaper-8-lcm", name: "DreamShaper 8 LCM", kind: None },
            ProviderModel { id: "@cf/runwayml/stable-diffusion-v1-5-img2img", name: "Stable Diffusion v1.5 Img2Img", kind: None },
            ProviderModel { id: "@cf/runwayml/stable-diffusion-v1-5-inpainting", name: "Stable Diffusion v1.5 Inpainting", kind: None },
            ProviderModel { id: "@cf/stabilityai/stable-diffusion-xl-base-1.0", name: "SDXL Base 1.0", kind: None },
        ],
        service_kinds: &["llm", "image"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "coqui",
        priority: 0,
        alias: "coqui",
        ui_alias: None,
        display: ProviderDisplay { name: "Coqui TTS", icon: Some("record_voice_over"), color: Some("#10B981"), text_icon: Some("CQ"), website: Some("https://github.com/coqui-ai/TTS"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("http://localhost:5002/api/tts"), format: Some("coqui"), ..DEFAULT_TRANSPORT },
        models: &[],
        service_kinds: &["tts"],
        hidden: true,
    },
    ProviderRegistryEntry {
        id: "edge-tts",
        priority: 0,
        alias: "edge-tts",
        ui_alias: None,
        display: ProviderDisplay { name: "Edge TTS", icon: Some("record_voice_over"), color: Some("#0078D4"), text_icon: Some("ET"), website: None, notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("edge-tts"), format: Some("edge-tts"), ..DEFAULT_TRANSPORT },
        models: &[],
        service_kinds: &["tts"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "gemini",
        priority: 50,
        alias: "gemini",
        ui_alias: None,
        display: ProviderDisplay { name: "Gemini", icon: Some("diamond"), color: Some("#4285F4"), text_icon: Some("GE"), website: Some("https://ai.google.dev"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://generativelanguage.googleapis.com/v1beta/models"), format: Some("gemini"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", kind: None },
            ProviderModel { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash", kind: None },
            ProviderModel { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash", kind: None },
            ProviderModel { id: "gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite", kind: None },
            ProviderModel { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview", kind: None },
            ProviderModel { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", kind: None },
            ProviderModel { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview", kind: None },
            ProviderModel { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", kind: None },
            ProviderModel { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", kind: None },
            ProviderModel { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite", kind: None },
            ProviderModel { id: "gemma-4-31b-it", name: "Gemma 4 31B IT", kind: None },
            ProviderModel { id: "gemini-embedding-2-preview", name: "Gemini Embedding 2 Preview", kind: Some("embedding") },
            ProviderModel { id: "gemini-embedding-001", name: "Gemini Embedding 001", kind: Some("embedding") },
            ProviderModel { id: "text-embedding-005", name: "Text Embedding 005", kind: Some("embedding") },
            ProviderModel { id: "text-embedding-004", name: "Text Embedding 004 (Legacy)", kind: Some("embedding") },
            ProviderModel { id: "gemini-3.1-flash-image-preview", name: "Gemini 3.1 Flash Image (Nano Banana 2)", kind: Some("image") },
            ProviderModel { id: "gemini-3-pro-image-preview", name: "Gemini 3 Pro Image (Nano Banana Pro)", kind: Some("image") },
            ProviderModel { id: "gemini-2.5-flash-image", name: "Gemini 2.5 Flash Image (Nano Banana)", kind: Some("image") },
            ProviderModel { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro (Best)", kind: None },
            ProviderModel { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", kind: None },
            ProviderModel { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite (Cheapest)", kind: None },
            ProviderModel { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", kind: None },
            ProviderModel { id: "gemini-3.1-flash-tts-preview", name: "Gemini 3.1 Flash TTS", kind: Some("tts") },
            ProviderModel { id: "gemini-2.5-flash-preview-tts", name: "Gemini 2.5 Flash TTS", kind: Some("tts") },
            ProviderModel { id: "gemini-2.5-pro-preview-tts", name: "Gemini 2.5 Pro TTS", kind: Some("tts") },
            ProviderModel { id: "embedding-001", name: "Embedding 001", kind: Some("embedding") },
        ],
        service_kinds: &["llm", "embedding", "image", "imageToText", "webSearch", "tts", "stt"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "google-tts",
        priority: 0,
        alias: "google-tts",
        ui_alias: None,
        display: ProviderDisplay { name: "Google TTS", icon: Some("record_voice_over"), color: Some("#4285F4"), text_icon: Some("GT"), website: None, notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("google-tts"), format: Some("google-tts"), ..DEFAULT_TRANSPORT },
        models: &[],
        service_kinds: &["tts"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "kilo-gateway",
        priority: 0,
        alias: "kgw",
        ui_alias: Some("kgw"),
        display: ProviderDisplay { name: "Kilo Gateway", icon: Some("login"), color: Some("#8B5CF6"), text_icon: Some("KG"), website: Some("https://kilo.ai"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://api.kilo.ai/api/gateway/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "kilo-auto/free", name: "Kilo Auto Free", kind: None },
            ProviderModel { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "Nemotron 3 Super 120B (Free)", kind: None },
            ProviderModel { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "Nemotron 3 Ultra 550B (Free)", kind: None },
            ProviderModel { id: "kwaipilot/kat-coder-pro-v2.5:free", name: "Kat Coder Pro v2.5 (Free)", kind: None },
            ProviderModel { id: "kilo-auto/frontier", name: "Kilo Auto Frontier", kind: None },
            ProviderModel { id: "kilo-auto/balanced", name: "Kilo Auto Balanced", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "kimchi",
        priority: 95,
        alias: "kimchi",
        ui_alias: Some("kimchi"),
        display: ProviderDisplay { name: "Kimchi", icon: Some("restaurant"), color: Some("#FF521D"), text_icon: Some("KC"), website: Some("https://kimchi.dev"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport {
            base_url: Some("https://llm.kimchi.dev/openai/v1/chat/completions"),
            format: Some("openai"),
            headers: &[("User-Agent", "kimchi/0.1.50")],
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "minimax-m3", name: "MiniMax-M3", kind: None },
            ProviderModel { id: "kimi-k2.7", name: "Kimi-K2.7", kind: None },
            ProviderModel { id: "kimi-k2.6", name: "Kimi-K2.6", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi-K2.5", kind: None },
            ProviderModel { id: "nemotron-3-ultra-fp4", name: "Nemotron 3 Ultra FP4", kind: None },
            ProviderModel { id: "minimax-m2.7", name: "MiniMax-M2.7", kind: None },
            ProviderModel { id: "claude-opus-4-6", name: "Claude Opus 4.6", kind: None },
            ProviderModel { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", kind: None },
        ],
        service_kinds: &["llm", "imageToText"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "local-device",
        priority: 0,
        alias: "local-device",
        ui_alias: None,
        display: ProviderDisplay { name: "Local Device", icon: Some("speaker"), color: Some("#64748B"), text_icon: Some("LD"), website: None, notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("local-device"), format: Some("local-device"), ..DEFAULT_TRANSPORT },
        models: &[],
        service_kinds: &["tts"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "nvidia",
        priority: 20,
        alias: "nvidia",
        ui_alias: None,
        display: ProviderDisplay { name: "NVIDIA NIM", icon: Some("developer_board"), color: Some("#76B900"), text_icon: Some("NV"), website: Some("https://developer.nvidia.com/nim"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://integrate.api.nvidia.com/v1/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "minimaxai/minimax-m2.7", name: "MiniMax M2.7", kind: None },
            ProviderModel { id: "minimaxai/minimax-m3", name: "MiniMax M3", kind: None },
            ProviderModel { id: "z-ai/glm-5.2", name: "GLM 5.2", kind: None },
            ProviderModel { id: "deepseek-ai/deepseek-v4-pro", name: "DeepSeek V4 Pro", kind: None },
            ProviderModel { id: "deepseek-ai/deepseek-v4-flash", name: "DeepSeek V4 Flash", kind: None },
            ProviderModel { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6", kind: None },
            ProviderModel { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra", kind: None },
            ProviderModel { id: "nvidia/nv-embedqa-e5-v5", name: "NV EmbedQA E5 v5", kind: Some("embedding") },
            ProviderModel { id: "nvidia/parakeet-ctc-1.1b-asr", name: "Parakeet CTC 1.1B", kind: Some("stt") },
            ProviderModel { id: "fastpitch", name: "FastPitch", kind: Some("tts") },
            ProviderModel { id: "tacotron2", name: "Tacotron2", kind: Some("tts") },
        ],
        service_kinds: &["llm", "tts", "embedding"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "ollama",
        priority: 30,
        alias: "ollama",
        ui_alias: None,
        display: ProviderDisplay { name: "Ollama Cloud", icon: Some("cloud"), color: Some("#ffffffff"), text_icon: Some("OL"), website: Some("https://ollama.com"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://ollama.com/api/chat"), format: Some("ollama"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "gpt-oss:120b", name: "GPT OSS 120B", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi K2.5", kind: None },
            ProviderModel { id: "glm-5", name: "GLM 5", kind: None },
            ProviderModel { id: "minimax-m2.5", name: "MiniMax M2.5", kind: None },
            ProviderModel { id: "glm-4.7-flash", name: "GLM 4.7 Flash", kind: None },
            ProviderModel { id: "qwen3.5", name: "Qwen3.5", kind: None },
            ProviderModel { id: "minimax-m3", name: "MiniMax M3", kind: None },
        ],
        service_kinds: &["llm", "webFetch"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "openrouter",
        priority: 10,
        alias: "openrouter",
        ui_alias: None,
        display: ProviderDisplay { name: "OpenRouter", icon: Some("router"), color: Some("#F97316"), text_icon: Some("OR"), website: Some("https://openrouter.ai"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://openrouter.ai/api/v1/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "openai/text-embedding-3-large", name: "OpenAI Text Embedding 3 Large", kind: Some("embedding") },
            ProviderModel { id: "openai/text-embedding-3-small", name: "OpenAI Text Embedding 3 Small", kind: Some("embedding") },
            ProviderModel { id: "openai/text-embedding-ada-002", name: "OpenAI Text Embedding Ada 002", kind: Some("embedding") },
            ProviderModel { id: "qwen/qwen3-embedding-8b", name: "Qwen3 Embedding 8B", kind: Some("embedding") },
            ProviderModel { id: "perplexity/pplx-embed-v1-4b", name: "Perplexity Embed V1 4B", kind: Some("embedding") },
            ProviderModel { id: "perplexity/pplx-embed-v1-0.6b", name: "Perplexity Embed V1 0.6B", kind: Some("embedding") },
            ProviderModel { id: "nvidia/llama-nemotron-embed-vl-1b-v2:free", name: "NVIDIA Nemotron Embed VL 1B V2 (Free)", kind: Some("embedding") },
            ProviderModel { id: "openai/gpt-4o-mini-tts", name: "GPT-4o Mini TTS", kind: Some("tts") },
            ProviderModel { id: "openai/tts-1-hd", name: "TTS-1 HD", kind: Some("tts") },
            ProviderModel { id: "openai/tts-1", name: "TTS-1", kind: Some("tts") },
            ProviderModel { id: "openai/dall-e-3", name: "DALL-E 3 (via OpenRouter)", kind: Some("image") },
            ProviderModel { id: "openai/gpt-image-1", name: "GPT Image 1 (via OpenRouter)", kind: Some("image") },
            ProviderModel { id: "google/imagen-3.0-generate-002", name: "Imagen 3 (via OpenRouter)", kind: Some("image") },
            ProviderModel { id: "black-forest-labs/FLUX.1-schnell", name: "FLUX.1 Schnell (via OpenRouter)", kind: Some("image") },
        ],
        service_kinds: &["llm", "embedding", "tts", "imageToText"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "poolside",
        priority: 60,
        alias: "poolside",
        ui_alias: Some("ps"),
        display: ProviderDisplay { name: "Poolside", icon: Some("water_drop"), color: Some("#0EA5E9"), text_icon: Some("PS"), website: Some("https://poolside.ai"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://inference.poolside.ai/v1/chat/completions"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "poolside/laguna-s-2.1", name: "Laguna S 2.1", kind: None },
            ProviderModel { id: "poolside/laguna-xs-2.1", name: "Laguna XS 2.1", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "searxng",
        priority: 0,
        alias: "searxng",
        ui_alias: None,
        display: ProviderDisplay { name: "SearXNG", icon: Some("saved_search"), color: Some("#3B82F6"), text_icon: Some("SX"), website: Some("https://docs.searxng.org"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some(""), ..DEFAULT_TRANSPORT },
        models: &[],
        service_kinds: &["webSearch"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "tortoise",
        priority: 0,
        alias: "tortoise",
        ui_alias: None,
        display: ProviderDisplay { name: "Tortoise TTS", icon: Some("record_voice_over"), color: Some("#7C3AED"), text_icon: Some("TT"), website: Some("https://github.com/neonbjb/tortoise-tts"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("http://localhost:5000/api/tts"), format: Some("tortoise"), ..DEFAULT_TRANSPORT },
        models: &[],
        service_kinds: &["tts"],
        hidden: true,
    },
    ProviderRegistryEntry {
        id: "vertex",
        priority: 40,
        alias: "vertex",
        ui_alias: Some("vx"),
        display: ProviderDisplay { name: "Vertex AI", icon: Some("cloud"), color: Some("#4285F4"), text_icon: Some("VX"), website: Some("https://cloud.google.com/vertex-ai"), notice: None },
        category: ProviderCategory::FreeTier,
        transport: ProviderTransport { base_url: Some("https://aiplatform.googleapis.com"), format: Some("vertex"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview", kind: None },
            ProviderModel { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", kind: None },
            ProviderModel { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview", kind: None },
            ProviderModel { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", kind: None },
        ],
        service_kinds: &["llm", "imageToText"],
        hidden: false,
    },
    // ── free ──
    ProviderRegistryEntry {
        id: "devin-cli",
        priority: 0,
        alias: "dv",
        ui_alias: Some("dv"),
        display: ProviderDisplay { name: "Devin CLI", icon: Some("smart_toy"), color: Some("#6366F1"), text_icon: Some("DV"), website: Some("https://devin.ai"), notice: None },
        category: ProviderCategory::Free,
        transport: ProviderTransport { base_url: Some("devin://acp/stdio"), format: Some("openai"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "swe-1.6-fast", name: "SWE-1.6 Fast", kind: None },
            ProviderModel { id: "swe-1.6", name: "SWE-1.6", kind: None },
            ProviderModel { id: "swe-1.5-fast", name: "SWE-1.5 Fast", kind: None },
            ProviderModel { id: "swe-1.5", name: "SWE-1.5", kind: None },
            ProviderModel { id: "claude-opus-4.7-max", name: "Claude Opus 4.7 Max", kind: None },
            ProviderModel { id: "claude-opus-4.7-high", name: "Claude Opus 4.7 High", kind: None },
            ProviderModel { id: "claude-opus-4.7-medium", name: "Claude Opus 4.7 Medium", kind: None },
            ProviderModel { id: "claude-opus-4.7-low", name: "Claude Opus 4.7 Low", kind: None },
            ProviderModel { id: "claude-sonnet-4.6-thinking-1m", name: "Claude Sonnet 4.6 Thinking 1M", kind: None },
            ProviderModel { id: "claude-sonnet-4.6-thinking", name: "Claude Sonnet 4.6 Thinking", kind: None },
            ProviderModel { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", kind: None },
            ProviderModel { id: "claude-opus-4.6-thinking", name: "Claude Opus 4.6 Thinking", kind: None },
            ProviderModel { id: "claude-opus-4.6", name: "Claude Opus 4.6", kind: None },
            ProviderModel { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", kind: None },
            ProviderModel { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", kind: None },
            ProviderModel { id: "gpt-5.5-xhigh", name: "GPT-5.5 XHigh", kind: None },
            ProviderModel { id: "gpt-5.5-high", name: "GPT-5.5 High", kind: None },
            ProviderModel { id: "gpt-5.5-medium", name: "GPT-5.5 Medium", kind: None },
            ProviderModel { id: "gpt-5.5-low", name: "GPT-5.5 Low", kind: None },
            ProviderModel { id: "gpt-5.4-high", name: "GPT-5.4 High", kind: None },
            ProviderModel { id: "gpt-5.4-medium", name: "GPT-5.4 Medium", kind: None },
            ProviderModel { id: "gpt-5.4-low", name: "GPT-5.4 Low", kind: None },
            ProviderModel { id: "gpt-5.3-codex-high", name: "GPT-5.3 Codex High", kind: None },
            ProviderModel { id: "gpt-5.3-codex-medium", name: "GPT-5.3 Codex Medium", kind: None },
            ProviderModel { id: "gpt-5.3-codex-low", name: "GPT-5.3 Codex Low", kind: None },
            ProviderModel { id: "gpt-5.2-high", name: "GPT-5.2 High", kind: None },
            ProviderModel { id: "gpt-5.2-medium", name: "GPT-5.2 Medium", kind: None },
            ProviderModel { id: "gpt-5.2-low", name: "GPT-5.2 Low", kind: None },
            ProviderModel { id: "gemini-3.1-pro-high", name: "Gemini 3.1 Pro High", kind: None },
            ProviderModel { id: "gemini-3.1-pro-low", name: "Gemini 3.1 Pro Low", kind: None },
            ProviderModel { id: "gemini-3.0-flash-high", name: "Gemini 3 Flash High", kind: None },
            ProviderModel { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", kind: None },
            ProviderModel { id: "deepseek-v4", name: "DeepSeek V4", kind: None },
            ProviderModel { id: "kimi-k2.6", name: "Kimi K2.6", kind: None },
            ProviderModel { id: "glm-5.1", name: "GLM-5.1", kind: None },
        ],
        service_kinds: &[],
        hidden: true,
    },
    ProviderRegistryEntry {
        id: "gemini-cli",
        priority: 20,
        alias: "gc",
        ui_alias: Some("gc"),
        display: ProviderDisplay { name: "Gemini CLI", icon: Some("terminal"), color: Some("#4285F4"), text_icon: None, website: Some("https://github.com/google-gemini/gemini-cli"), notice: None },
        category: ProviderCategory::Free,
        transport: ProviderTransport { base_url: Some("https://cloudcode-pa.googleapis.com/v1internal"), format: Some("gemini-cli"), ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview", kind: None },
            ProviderModel { id: "gemini-3-pro-preview", name: "Gemini 3 Pro Preview", kind: None },
            ProviderModel { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview", kind: None },
            ProviderModel { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", kind: None },
            ProviderModel { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", kind: None },
            ProviderModel { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", kind: None },
            ProviderModel { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "kiro",
        priority: 10,
        alias: "kr",
        ui_alias: Some("kr"),
        display: ProviderDisplay { name: "Kiro AI", icon: Some("psychology_alt"), color: Some("#FF6B35"), text_icon: None, website: Some("https://kiro.dev"), notice: None },
        category: ProviderCategory::Free,
        transport: ProviderTransport {
            base_url: Some("https://runtime.us-east-1.kiro.dev/generateAssistantResponse"),
            format: Some("kiro"),
            headers: &[
                ("Content-Type", "application/json"),
                ("Accept", "application/vnd.amazon.eventstream"),
                ("User-Agent", "AWS-SDK-JS/3.0.0 kiro-ide/1.0.0"),
                ("X-Amz-User-Agent", "aws-sdk-js/3.0.0 kiro-ide/1.0.0"),
            ],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "claude-opus-5", name: "Claude Opus 5", kind: None },
            ProviderModel { id: "claude-opus-5-thinking", name: "Claude Opus 5 (Thinking)", kind: None },
            ProviderModel { id: "claude-opus-5-agentic", name: "Claude Opus 5 (Agentic)", kind: None },
            ProviderModel { id: "claude-opus-5-thinking-agentic", name: "Claude Opus 5 (Thinking + Agentic)", kind: None },
            ProviderModel { id: "claude-opus-4.8", name: "Claude Opus 4.8", kind: None },
            ProviderModel { id: "claude-opus-4.8-thinking", name: "Claude Opus 4.8 (Thinking)", kind: None },
            ProviderModel { id: "claude-opus-4.8-agentic", name: "Claude Opus 4.8 (Agentic)", kind: None },
            ProviderModel { id: "claude-opus-4.8-thinking-agentic", name: "Claude Opus 4.8 (Thinking + Agentic)", kind: None },
            ProviderModel { id: "claude-opus-4.7", name: "Claude Opus 4.7", kind: None },
            ProviderModel { id: "claude-opus-4.7-thinking", name: "Claude Opus 4.7 (Thinking)", kind: None },
            ProviderModel { id: "claude-opus-4.7-agentic", name: "Claude Opus 4.7 (Agentic)", kind: None },
            ProviderModel { id: "claude-opus-4.7-thinking-agentic", name: "Claude Opus 4.7 (Thinking + Agentic)", kind: None },
            ProviderModel { id: "claude-opus-4.5", name: "Claude Opus 4.5", kind: None },
            ProviderModel { id: "claude-opus-4.5-thinking", name: "Claude Opus 4.5 (Thinking)", kind: None },
            ProviderModel { id: "claude-opus-4.5-agentic", name: "Claude Opus 4.5 (Agentic)", kind: None },
            ProviderModel { id: "claude-opus-4.5-thinking-agentic", name: "Claude Opus 4.5 (Thinking + Agentic)", kind: None },
            ProviderModel { id: "claude-sonnet-5", name: "Claude Sonnet 5", kind: None },
            ProviderModel { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", kind: None },
            ProviderModel { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", kind: None },
            ProviderModel { id: "deepseek-3.2", name: "DeepSeek 3.2", kind: None },
            ProviderModel { id: "qwen3-coder-next", name: "Qwen3 Coder Next", kind: None },
            ProviderModel { id: "glm-5", name: "GLM 5", kind: None },
            ProviderModel { id: "MiniMax-M2.5", name: "MiniMax M2.5", kind: None },
            ProviderModel { id: "gpt-5.6-sol", name: "GPT 5.6 Sol", kind: None },
            ProviderModel { id: "gpt-5.6-terra", name: "GPT 5.6 Terra", kind: None },
            ProviderModel { id: "gpt-5.6-luna", name: "GPT 5.6 Luna", kind: None },
            ProviderModel { id: "claude-sonnet-5-thinking", name: "Claude Sonnet 5 (Thinking)", kind: None },
            ProviderModel { id: "claude-sonnet-4.5-thinking", name: "Claude Sonnet 4.5 (Thinking)", kind: None },
            ProviderModel { id: "claude-haiku-4.5-thinking", name: "Claude Haiku 4.5 (Thinking)", kind: None },
            ProviderModel { id: "gpt-5.6-sol-thinking", name: "GPT 5.6 Sol (Thinking)", kind: None },
            ProviderModel { id: "gpt-5.6-terra-thinking", name: "GPT 5.6 Terra (Thinking)", kind: None },
            ProviderModel { id: "gpt-5.6-luna-thinking", name: "GPT 5.6 Luna (Thinking)", kind: None },
            ProviderModel { id: "claude-sonnet-5-agentic", name: "Claude Sonnet 5 (Agentic)", kind: None },
            ProviderModel { id: "claude-sonnet-4.5-agentic", name: "Claude Sonnet 4.5 (Agentic)", kind: None },
            ProviderModel { id: "claude-haiku-4.5-agentic", name: "Claude Haiku 4.5 (Agentic)", kind: None },
            ProviderModel { id: "gpt-5.6-sol-agentic", name: "GPT 5.6 Sol (Agentic)", kind: None },
            ProviderModel { id: "gpt-5.6-terra-agentic", name: "GPT 5.6 Terra (Agentic)", kind: None },
            ProviderModel { id: "gpt-5.6-luna-agentic", name: "GPT 5.6 Luna (Agentic)", kind: None },
            ProviderModel { id: "claude-sonnet-5-thinking-agentic", name: "Claude Sonnet 5 (Thinking + Agentic)", kind: None },
            ProviderModel { id: "claude-sonnet-4.5-thinking-agentic", name: "Claude Sonnet 4.5 (Thinking + Agentic)", kind: None },
            ProviderModel { id: "claude-haiku-4.5-thinking-agentic", name: "Claude Haiku 4.5 (Thinking + Agentic)", kind: None },
            ProviderModel { id: "gpt-5.6-sol-thinking-agentic", name: "GPT 5.6 Sol (Thinking + Agentic)", kind: None },
            ProviderModel { id: "gpt-5.6-terra-thinking-agentic", name: "GPT 5.6 Terra (Thinking + Agentic)", kind: None },
            ProviderModel { id: "gpt-5.6-luna-thinking-agentic", name: "GPT 5.6 Luna (Thinking + Agentic)", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "mimo-free",
        priority: 50,
        alias: "mmf",
        ui_alias: Some("mmf"),
        display: ProviderDisplay { name: "MiMo Code Free", icon: Some("smart_toy"), color: Some("#FF6900"), text_icon: Some("MF"), website: None, notice: None },
        category: ProviderCategory::Free,
        transport: ProviderTransport { base_url: Some("https://api.xiaomimimo.com/api/free-ai/openai/chat"), ..DEFAULT_TRANSPORT },
        models: &[ProviderModel { id: "mimo-auto", name: "MiMo Auto", kind: None }],
        service_kinds: &[],
        hidden: true,
    },
    ProviderRegistryEntry {
        id: "opencode",
        priority: 40,
        alias: "oc",
        ui_alias: Some("oc"),
        display: ProviderDisplay { name: "OpenCode Free", icon: Some("terminal"), color: Some("#E87040"), text_icon: Some("OC"), website: None, notice: None },
        category: ProviderCategory::Free,
        transport: ProviderTransport { base_url: Some("https://opencode.ai"), headers: &[("x-opencode-client", "desktop")], ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "muse-spark-1.2-contributor-free", name: "Muse Spark 1.2 Contributor Free", kind: None },
            ProviderModel { id: "muse-spark-1.3-contributor-free", name: "Muse Spark 1.3 Contributor Free", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
];
