//! OAuth category providers (19 entries).
//! Ported from open-sse/providers/registry/ for category: "oauth"

use super::*;

pub static ENTRIES: &[ProviderRegistryEntry] = &[
    ProviderRegistryEntry {
        id: "antigravity",
        priority: 20,
        alias: "ag",
        ui_alias: Some("ag"),
        display: ProviderDisplay { name: "Antigravity", icon: Some("rocket_launch"), color: Some("#F59E0B"), text_icon: None, website: Some("https://antigravity.google"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport { base_url: None, format: Some("antigravity"), headers: &[("User-Agent", "AntigravityIDE/0.1.0")], ..DEFAULT_TRANSPORT },
        models: &[
            ProviderModel { id: "gemini-3.8-flash-high", name: "Gemini 3.8 Flash (High)", kind: None },
            ProviderModel { id: "gemini-3.8-flash-medium", name: "Gemini 3.8 Flash (Medium)", kind: None },
            ProviderModel { id: "gemini-3.8-flash-low", name: "Gemini 3.8 Flash (Low)", kind: None },
            ProviderModel { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", kind: None },
            ProviderModel { id: "gemini-3.7-flash-high", name: "Gemini 3.7 Flash (High)", kind: None },
            ProviderModel { id: "gemini-3.7-flash-medium", name: "Gemini 3.7 Flash (Medium)", kind: None },
            ProviderModel { id: "gemini-3.7-flash-low", name: "Gemini 3.7 Flash (Low)", kind: None },
            ProviderModel { id: "gemini-3.6-flash-high", name: "Gemini 3.6 Flash (High)", kind: None },
            ProviderModel { id: "gemini-3.6-flash-medium", name: "Gemini 3.6 Flash (Medium)", kind: None },
            ProviderModel { id: "gemini-3.6-flash-low", name: "Gemini 3.6 Flash (Low)", kind: None },
            ProviderModel { id: "gemini-3.5-flash-high", name: "Gemini 3.5 Flash (High)", kind: None },
            ProviderModel { id: "gemini-3-flash-agent", name: "Gemini 3.5 Flash (High)", kind: None },
            ProviderModel { id: "gemini-3.5-flash-low", name: "Gemini 3.5 Flash (Medium)", kind: None },
            ProviderModel { id: "gemini-3.5-flash-extra-low", name: "Gemini 3.5 Flash (Low)", kind: None },
            ProviderModel { id: "gemini-pro-agent", name: "Gemini 3.1 Pro (High)", kind: None },
            ProviderModel { id: "gemini-3.1-pro-low", name: "Gemini 3.1 Pro (Low)", kind: None },
            ProviderModel { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6 (Thinking)", kind: None },
            ProviderModel { id: "claude-opus-4-6-thinking", name: "Claude Opus 4.6 (Thinking)", kind: None },
            ProviderModel { id: "gpt-oss-120b-medium", name: "GPT-OSS 120B (Medium)", kind: None },
            ProviderModel { id: "gemini-3-flash", name: "Gemini 3 Flash", kind: None },
            ProviderModel { id: "gemini-3.1-flash-image", name: "Gemini 3.1 Flash (Image)", kind: Some("image") },
        ],
        service_kinds: &["llm", "image", "webSearch"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "claude",
        priority: 10,
        alias: "cc",
        ui_alias: Some("cc"),
        display: ProviderDisplay { name: "Claude Code", icon: Some("smart_toy"), color: Some("#D97757"), text_icon: None, website: Some("https://claude.ai"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api.anthropic.com/v1/messages"),
            format: Some("claude"),
            url_suffix: Some("?beta=true"),
            headers: &[
                ("anthropic-version", "2023-06-01"),
                ("Anthropic-Beta", "claude-code-20250219,interleaved-thinking-2025-05-14"),
            ],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "claude-opus-5", name: "Claude Opus 5", kind: None },
            ProviderModel { id: "claude-fable-5-1", name: "Claude Fable 5.1", kind: None },
            ProviderModel { id: "claude-fable-5", name: "Claude Fable 5", kind: None },
            ProviderModel { id: "claude-sonnet-5", name: "Claude Sonnet 5", kind: None },
            ProviderModel { id: "claude-haiku-4-5-20251001", name: "Claude 4.5 Haiku", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "cline",
        priority: 80,
        alias: "cl",
        ui_alias: Some("cl"),
        display: ProviderDisplay { name: "Cline", icon: Some("smart_toy"), color: Some("#5B9BD5"), text_icon: Some("CL"), website: Some("https://cline.bot"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api.cline.bot/api/v1/chat/completions"),
            format: None,
            headers: &[
                ("Content-Type", "application/json"),
                ("X-Cline-Version", "3.17.0"),
            ],
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7", kind: None },
            ProviderModel { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6", kind: None },
            ProviderModel { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6", kind: None },
            ProviderModel { id: "openai/gpt-5.3-codex", name: "GPT-5.3 Codex", kind: None },
            ProviderModel { id: "openai/gpt-5.4", name: "GPT-5.4", kind: None },
            ProviderModel { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview", kind: None },
            ProviderModel { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", kind: None },
            ProviderModel { id: "kwaipilot/kat-coder-pro", name: "KAT Coder Pro", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "clinepass",
        priority: 85,
        alias: "clinepass",
        ui_alias: Some("clinepass"),
        display: ProviderDisplay { name: "ClinePass", icon: Some("vpn_key"), color: Some("#5B9BD5"), text_icon: Some("CP"), website: Some("https://cline.bot"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api.cline.bot/api/v1/chat/completions"),
            format: None,
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "cline-pass/glm-5.2", name: "GLM-5.2 (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/kimi-k2.7-code", name: "Kimi K2.7 Code (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/kimi-k2.6", name: "Kimi K2.6 (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/deepseek-v4-pro", name: "DeepSeek V4 Pro (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/deepseek-v4-flash", name: "DeepSeek V4 Flash (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/mimo-v2.5", name: "MiMo-V2.5 (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/mimo-v2.5-pro", name: "MiMo-V2.5-Pro (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/minimax-m3", name: "MiniMax M3 (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/qwen3.7-max", name: "Qwen3.7 Max (ClinePass)", kind: None },
            ProviderModel { id: "cline-pass/qwen3.7-plus", name: "Qwen3.7 Plus (ClinePass)", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "codebuddy-cn",
        priority: 90,
        alias: "cbcn",
        ui_alias: Some("cbcn"),
        display: ProviderDisplay { name: "CodeBuddy CN", icon: Some("smart_toy"), color: Some("#006EFF"), text_icon: None, website: Some("https://copilot.tencent.com"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://copilot.tencent.com/v2/chat/completions"),
            force_stream: Some(true),
            headers: &[
                ("User-Agent", "CLI/2.108.1 CodeBuddy/2.108.1"),
                ("X-Product", "SaaS"),
                ("X-IDE-Type", "CLI"),
                ("X-IDE-Name", "CLI"),
                ("x-requested-with", "XMLHttpRequest"),
                ("x-codebuddy-request", "1"),
            ],
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "glm-5.2", name: "GLM-5.2", kind: None },
            ProviderModel { id: "glm-5.1", name: "GLM-5.1", kind: None },
            ProviderModel { id: "glm-5.0-turbo", name: "GLM-5.0-Turbo", kind: None },
            ProviderModel { id: "glm-5v-turbo", name: "GLM-5v-Turbo", kind: None },
            ProviderModel { id: "minimax-m3", name: "MiniMax-M3", kind: None },
            ProviderModel { id: "minimax-m2.7", name: "MiniMax-M2.7", kind: None },
            ProviderModel { id: "kimi-k2.7", name: "Kimi-K2.7-Code", kind: None },
            ProviderModel { id: "kimi-k2.6", name: "Kimi-K2.6", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi-K2.5", kind: None },
            ProviderModel { id: "hy3-preview", name: "Hy3 Preview", kind: None },
            ProviderModel { id: "hy3", name: "Hy3", kind: None },
            ProviderModel { id: "hy3-x", name: "Hy3 (Paid)", kind: None },
            ProviderModel { id: "hy4-preview", name: "Hy4-Preview", kind: None },
            ProviderModel { id: "hy4-preview-x", name: "Hy4-Preview (Paid)", kind: None },
            ProviderModel { id: "glm-5.3", name: "GLM-5.3", kind: None },
            ProviderModel { id: "glm-5.3-flash", name: "GLM-5.3-Flash", kind: None },
            ProviderModel { id: "kimi-k3-1", name: "Kimi-K3", kind: None },
            ProviderModel { id: "deepseek-v4-pro", name: "DeepSeek-V4-Pro", kind: None },
            ProviderModel { id: "deepseek-v4-flash", name: "DeepSeek-V4-Flash", kind: None },
            ProviderModel { id: "deepseek-v3-2-volc", name: "DeepSeek-V3.2", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "codebuddy-intl",
        priority: 90,
        alias: "cbai",
        ui_alias: Some("cbai"),
        display: ProviderDisplay { name: "CodeBuddy", icon: Some("smart_toy"), color: Some("#006EFF"), text_icon: None, website: Some("https://www.codebuddy.ai"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://www.codebuddy.ai/v2/chat/completions"),
            force_stream: Some(true),
            headers: &[
                ("User-Agent", "IDE/2.108.1 CodeBuddy/2.108.1"),
                ("X-Product", "SaaS"),
                ("X-IDE-Type", "IDE"),
                ("X-IDE-Name", "IDE"),
                ("x-requested-with", "XMLHttpRequest"),
                ("x-codebuddy-request", "1"),
            ],
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "glm-5.2", name: "GLM-5.2", kind: None },
            ProviderModel { id: "glm-5.1", name: "GLM-5.1", kind: None },
            ProviderModel { id: "glm-5.0", name: "GLM-5.0", kind: None },
            ProviderModel { id: "glm-5.0-turbo", name: "GLM-5.0-Turbo", kind: None },
            ProviderModel { id: "glm-5v-turbo", name: "GLM-5v-Turbo", kind: None },
            ProviderModel { id: "glm-4.7", name: "GLM-4.7", kind: None },
            ProviderModel { id: "minimax-m3", name: "MiniMax-M3", kind: None },
            ProviderModel { id: "minimax-m2.7", name: "MiniMax-M2.7", kind: None },
            ProviderModel { id: "kimi-k2.7", name: "Kimi-K2.7-Code", kind: None },
            ProviderModel { id: "kimi-k2.6", name: "Kimi-K2.6", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi-K2.5", kind: None },
            ProviderModel { id: "hy3-preview", name: "Hy3 Preview", kind: None },
            ProviderModel { id: "deepseek-v4-pro", name: "DeepSeek-V4-Pro", kind: None },
            ProviderModel { id: "deepseek-v4-flash", name: "DeepSeek-V4-Flash", kind: None },
            ProviderModel { id: "deepseek-v3-2-volc", name: "DeepSeek-V3.2", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "codex",
        priority: 30,
        alias: "cx",
        ui_alias: Some("cx"),
        display: ProviderDisplay { name: "OpenAI Codex", icon: Some("code"), color: Some("#3B82F6"), text_icon: None, website: Some("https://chatgpt.com/codex"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://chatgpt.com/backend-api/codex/responses"),
            format: Some("openai-responses"),
            force_stream: Some(true),
            headers: &[
                ("originator", "codex_cli_rs"),
                ("User-Agent", "codex_cli_rs/0.136.0"),
            ],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "gpt-5.6-sol", name: "GPT 5.6 Sol", kind: None },
            ProviderModel { id: "gpt-5.6-sol-review", name: "GPT 5.6 Sol Review", kind: None },
            ProviderModel { id: "gpt-5.6-terra", name: "GPT 5.6 Terra", kind: None },
            ProviderModel { id: "gpt-5.6-terra-review", name: "GPT 5.6 Terra Review", kind: None },
            ProviderModel { id: "gpt-5.6-luna", name: "GPT 5.6 Luna", kind: None },
            ProviderModel { id: "gpt-5.6-luna-review", name: "GPT 5.6 Luna Review", kind: None },
            ProviderModel { id: "gpt-5.5", name: "GPT 5.5", kind: None },
            ProviderModel { id: "gpt-5.5-review", name: "GPT 5.5 Review", kind: None },
            ProviderModel { id: "gpt-5.4", name: "GPT 5.4", kind: None },
            ProviderModel { id: "gpt-5.4-review", name: "GPT 5.4 Review", kind: None },
            ProviderModel { id: "gpt-5.4-mini", name: "GPT 5.4 Mini", kind: None },
            ProviderModel { id: "gpt-5.4-mini-review", name: "GPT 5.4 Mini Review", kind: None },
            ProviderModel { id: "gpt-5.3-codex-spark", name: "GPT 5.3 Codex Spark", kind: None },
            ProviderModel { id: "gpt-5.3-codex-spark-review", name: "GPT 5.3 Codex Spark Review", kind: None },
            ProviderModel { id: "gpt-5.5-image", name: "GPT 5.5 Image", kind: Some("image") },
            ProviderModel { id: "gpt-5.4-image", name: "GPT 5.4 Image", kind: Some("image") },
            ProviderModel { id: "gpt-5.3-image", name: "GPT 5.3 Image", kind: Some("image") },
        ],
        service_kinds: &["llm", "image"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "cursor",
        priority: 50,
        alias: "cu",
        ui_alias: Some("cu"),
        display: ProviderDisplay { name: "Cursor IDE", icon: Some("edit_note"), color: Some("#00D4AA"), text_icon: None, website: Some("https://cursor.com"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api2.cursor.sh"),
            format: Some("cursor"),
            chat_path: Some("/aiserver.v1.ChatService/StreamUnifiedChatWithTools"),
            client_version: Some("3.12.17"),
            headers: &[
                ("connect-accept-encoding", "gzip"),
                ("connect-protocol-version", "1"),
                ("Content-Type", "application/connect+proto"),
                ("User-Agent", "connect-es/1.6.1"),
            ],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "default", name: "Auto (Server Picks)", kind: None },
            ProviderModel { id: "claude-4.5-opus-high-thinking", name: "Claude 4.5 Opus High Thinking", kind: None },
            ProviderModel { id: "claude-4.5-opus-high", name: "Claude 4.5 Opus High", kind: None },
            ProviderModel { id: "claude-4.5-sonnet-thinking", name: "Claude 4.5 Sonnet Thinking", kind: None },
            ProviderModel { id: "claude-4.5-sonnet", name: "Claude 4.5 Sonnet", kind: None },
            ProviderModel { id: "claude-4.5-haiku", name: "Claude 4.5 Haiku", kind: None },
            ProviderModel { id: "claude-4.5-opus", name: "Claude 4.5 Opus", kind: None },
            ProviderModel { id: "gpt-5.2-codex", name: "GPT 5.2 Codex", kind: None },
            ProviderModel { id: "claude-4.6-opus-max", name: "Claude 4.6 Opus Max", kind: None },
            ProviderModel { id: "claude-4.6-sonnet-medium-thinking", name: "Claude 4.6 Sonnet Medium Thinking", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi K2.5", kind: None },
            ProviderModel { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview", kind: None },
            ProviderModel { id: "gpt-5.2", name: "GPT 5.2", kind: None },
            ProviderModel { id: "gpt-5.3-codex", name: "GPT 5.3 Codex", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "github",
        priority: 40,
        alias: "gh",
        ui_alias: Some("gh"),
        display: ProviderDisplay { name: "GitHub Copilot", icon: Some("code"), color: Some("#333333"), text_icon: None, website: Some("https://github.com/features/copilot"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api.githubcopilot.com/chat/completions"),
            headers: &[
                ("copilot-integration-id", "vscode-chat"),
                ("editor-version", "vscode/1.110.0"),
                ("editor-plugin-version", "copilot-chat/0.38.0"),
                ("user-agent", "GitHubCopilotChat/0.38.0"),
                ("openai-intent", "conversation-panel"),
                ("x-github-api-version", "2025-04-01"),
                ("x-vscode-user-agent-library-version", "electron-fetch"),
                ("X-Initiator", "user"),
                ("Accept", "application/json"),
                ("Content-Type", "application/json"),
            ],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "gpt-5.2", name: "GPT-5.2", kind: None },
            ProviderModel { id: "gpt-5.2-codex", name: "GPT-5.2 Codex", kind: None },
            ProviderModel { id: "gpt-5.3-codex", name: "GPT-5.3 Codex", kind: None },
            ProviderModel { id: "gpt-5.4", name: "GPT-5.4", kind: None },
            ProviderModel { id: "gpt-5.4-mini", name: "GPT-5.4 Mini", kind: None },
            ProviderModel { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", kind: None },
            ProviderModel { id: "claude-opus-4.5", name: "Claude Opus 4.5", kind: None },
            ProviderModel { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", kind: None },
            ProviderModel { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", kind: None },
            ProviderModel { id: "claude-opus-4.6", name: "Claude Opus 4.6", kind: None },
            ProviderModel { id: "claude-opus-4.7", name: "Claude Opus 4.7", kind: None },
            ProviderModel { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", kind: None },
            ProviderModel { id: "gemini-3-flash-preview", name: "Gemini 3 Flash", kind: None },
            ProviderModel { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro", kind: None },
            ProviderModel { id: "grok-code-fast-1", name: "Grok Code Fast 1", kind: None },
            ProviderModel { id: "oswe-vscode-prime", name: "Raptor Mini", kind: None },
            ProviderModel { id: "goldeneye-free-auto", name: "GoldenEye", kind: None },
            ProviderModel { id: "text-embedding-3-small", name: "Text Embedding 3 Small (GitHub)", kind: Some("embedding") },
            ProviderModel { id: "text-embedding-3-large", name: "Text Embedding 3 Large (GitHub)", kind: Some("embedding") },
        ],
        service_kinds: &["llm", "embedding"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "gitlab",
        priority: 100,
        alias: "",
        ui_alias: None,
        display: ProviderDisplay { name: "GitLab Duo", icon: Some("code"), color: Some("#FC6D26"), text_icon: Some("GL"), website: Some("https://gitlab.com"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://gitlab.com/api/v4/chat/completions"),
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[],
        service_kinds: &[],
        hidden: true,
    },
    ProviderRegistryEntry {
        id: "grok-cli",
        priority: 275,
        alias: "gcli",
        ui_alias: Some("gcli"),
        display: ProviderDisplay { name: "Grok CLI (Grok Build)", icon: Some("auto_awesome"), color: Some("#1DA1F2"), text_icon: Some("GC"), website: Some("https://x.ai"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://cli-chat-proxy.grok.com/responses"),
            format: Some("openai-responses"),
            force_stream: Some(true),
            headers: &[],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "grok-build", name: "Grok Build", kind: None },
            ProviderModel { id: "grok-4.5", name: "Grok 4.5", kind: None },
            ProviderModel { id: "grok-4.5-high", name: "Grok 4.5 (High)", kind: None },
            ProviderModel { id: "grok-4.5-medium", name: "Grok 4.5 (Medium)", kind: None },
            ProviderModel { id: "grok-4.5-low", name: "Grok 4.5 (Low)", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "iflow",
        priority: 110,
        alias: "if",
        ui_alias: None,
        display: ProviderDisplay { name: "iFlow AI", icon: Some("water_drop"), color: Some("#6366F1"), text_icon: None, website: Some("https://iflow.cn"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://apis.iflow.cn/v1/chat/completions"),
            headers: &[("User-Agent", "iFlow-Cli")],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus", kind: None },
            ProviderModel { id: "qwen3-max", name: "Qwen3 Max", kind: None },
            ProviderModel { id: "qwen3-vl-plus", name: "Qwen3 VL Plus", kind: None },
            ProviderModel { id: "qwen3-max-preview", name: "Qwen3 Max Preview", kind: None },
            ProviderModel { id: "qwen3-235b", name: "Qwen3 235B A22B", kind: None },
            ProviderModel { id: "qwen3-235b-a22b-instruct", name: "Qwen3 235B A22B Instruct", kind: None },
            ProviderModel { id: "qwen3-235b-a22b-thinking-2507", name: "Qwen3 235B A22B Thinking", kind: None },
            ProviderModel { id: "qwen3-32b", name: "Qwen3 32B", kind: None },
            ProviderModel { id: "kimi-k2", name: "Kimi K2", kind: None },
            ProviderModel { id: "deepseek-v3.2", name: "DeepSeek V3.2 Exp", kind: None },
            ProviderModel { id: "deepseek-v3.1", name: "DeepSeek V3.1 Terminus", kind: None },
            ProviderModel { id: "deepseek-v3", name: "DeepSeek V3 671B", kind: None },
            ProviderModel { id: "deepseek-r1", name: "DeepSeek R1", kind: None },
            ProviderModel { id: "glm-4.7", name: "GLM 4.7", kind: None },
            ProviderModel { id: "iflow-rome-30ba3b", name: "iFlow ROME", kind: None },
        ],
        service_kinds: &[],
        hidden: true,
    },
    ProviderRegistryEntry {
        id: "kilocode",
        priority: 70,
        alias: "kc",
        ui_alias: Some("kc"),
        display: ProviderDisplay { name: "Kilo Code", icon: Some("code"), color: Some("#FF6B35"), text_icon: Some("KC"), website: Some("https://kilocode.ai"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api.kilo.ai/api/openrouter/chat/completions"),
            format: None,
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "anthropic/claude-sonnet-4-20250514", name: "Claude Sonnet 4", kind: None },
            ProviderModel { id: "anthropic/claude-opus-4-20250514", name: "Claude Opus 4", kind: None },
            ProviderModel { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro", kind: None },
            ProviderModel { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash", kind: None },
            ProviderModel { id: "openai/gpt-4.1", name: "GPT-4.1", kind: None },
            ProviderModel { id: "openai/o3", name: "o3", kind: None },
            ProviderModel { id: "deepseek/deepseek-chat", name: "DeepSeek Chat", kind: None },
            ProviderModel { id: "deepseek/deepseek-reasoner", name: "DeepSeek Reasoner", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "kimi",
        priority: 170,
        alias: "kimi",
        ui_alias: None,
        display: ProviderDisplay { name: "Kimi", icon: Some("psychology"), color: Some("#1E3A8A"), text_icon: Some("KM"), website: Some("https://kimi.moonshot.cn"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api.kimi.com/coding/v1/messages"),
            format: Some("claude"),
            url_suffix: Some("?beta=true"),
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "kimi-k3", name: "Kimi K3", kind: None },
            ProviderModel { id: "k3", name: "Kimi K3 (Code)", kind: None },
            ProviderModel { id: "kimi-for-coding", name: "Kimi for Coding", kind: None },
            ProviderModel { id: "kimi-for-coding-highspeed", name: "Kimi for Coding Highspeed", kind: None },
            ProviderModel { id: "kimi-k2.7-code", name: "Kimi K2.7 Code", kind: None },
            ProviderModel { id: "kimi-k2.7-code-highspeed", name: "Kimi K2.7 Code Highspeed", kind: None },
            ProviderModel { id: "kimi-k2.6", name: "Kimi K2.6", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi K2.5", kind: None },
            ProviderModel { id: "kimi-k2.5-thinking", name: "Kimi K2.5 Thinking", kind: None },
            ProviderModel { id: "kimi-latest", name: "Kimi Latest", kind: None },
        ],
        service_kinds: &["llm", "webSearch"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "qoder",
        priority: 30,
        alias: "qd",
        ui_alias: Some("qd"),
        display: ProviderDisplay { name: "Qoder", icon: Some("water_drop"), color: Some("#EC4899"), text_icon: None, website: Some("https://qoder.com"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api3.qoder.sh/algo/api/v2/service/pro/sse/agent_chat_generation"),
            headers: &[],
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "ultimate", name: "Ultimate", kind: None },
            ProviderModel { id: "auto", name: "Auto", kind: None },
            ProviderModel { id: "performance", name: "Performance", kind: None },
            ProviderModel { id: "efficient", name: "Efficient", kind: None },
            ProviderModel { id: "qmodel_preview", name: "Qwen3.8-Max-Preview", kind: None },
            ProviderModel { id: "qmodel_latest", name: "Qwen3.7-Max", kind: None },
            ProviderModel { id: "qmodel", name: "Qwen3.7-Plus", kind: None },
            ProviderModel { id: "kmodel_latest", name: "Kimi-K3", kind: None },
            ProviderModel { id: "kmodel", name: "Kimi-K2.7-Code", kind: None },
            ProviderModel { id: "gm51model", name: "GLM-5.2", kind: None },
            ProviderModel { id: "dmodel", name: "DeepSeek-V4-Pro", kind: None },
            ProviderModel { id: "dfmodel", name: "DeepSeek-V4-Flash", kind: None },
            ProviderModel { id: "mmodel", name: "MiniMax-M3", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "trae",
        priority: 0,
        alias: "tr",
        ui_alias: Some("tr"),
        display: ProviderDisplay { name: "Trae", icon: Some("bolt"), color: Some("#FF6A00"), text_icon: Some("TR"), website: Some("https://www.trae.ai"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://core-normal.trae.ai/api/remote/v1"),
            format: Some("openai"),
            headers: &[
                ("X-Trae-Client-Type", "web"),
                ("X-Preferenced-Language", "en"),
                ("Referer", "https://solo.trae.ai/"),
            ],
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "Cloud-IDE-JWT" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "auto", name: "Auto (Server Picks)", kind: None },
            ProviderModel { id: "work", name: "Work (Fast)", kind: None },
            ProviderModel { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", kind: None },
            ProviderModel { id: "gemini-3-flash-solo", name: "Gemini 3 Flash", kind: None },
            ProviderModel { id: "minimax-m3", name: "MiniMax M3", kind: None },
            ProviderModel { id: "minimax-m2.7", name: "MiniMax M2.7", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi K2.5", kind: None },
            ProviderModel { id: "gpt-5.4", name: "GPT 5.4", kind: None },
            ProviderModel { id: "gpt-5.2", name: "GPT 5.2", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "windsurf",
        priority: 0,
        alias: "ws",
        ui_alias: Some("ws"),
        display: ProviderDisplay { name: "Windsurf", icon: Some("surfing"), color: Some("#14B8A6"), text_icon: None, website: Some("https://windsurf.com"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://server.codeium.com/exa.language_server_pb.LanguageServerService/GetChatMessage"),
            format: Some("openai"),
            headers: &[
                ("Content-Type", "application/grpc-web+proto"),
                ("Accept", "application/grpc-web+proto"),
                ("X-Grpc-Web", "1"),
            ],
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "Bearer" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "swe-1.6-fast", name: "SWE-1.6 Fast", kind: None },
            ProviderModel { id: "swe-1.6", name: "SWE-1.6", kind: None },
            ProviderModel { id: "swe-1.5-fast", name: "SWE-1.5 Fast", kind: None },
            ProviderModel { id: "swe-1.5", name: "SWE-1.5", kind: None },
            ProviderModel { id: "claude-opus-4.7-max", name: "Claude Opus 4.7 Max", kind: None },
            ProviderModel { id: "claude-opus-4.7-xhigh", name: "Claude Opus 4.7 XHigh", kind: None },
            ProviderModel { id: "claude-opus-4.7-high", name: "Claude Opus 4.7 High", kind: None },
            ProviderModel { id: "claude-opus-4.7-medium", name: "Claude Opus 4.7 Medium", kind: None },
            ProviderModel { id: "claude-opus-4.7-low", name: "Claude Opus 4.7 Low", kind: None },
            ProviderModel { id: "claude-opus-4.7-review", name: "Claude Opus 4.7 Review", kind: None },
            ProviderModel { id: "claude-sonnet-4.6-thinking-1m", name: "Claude Sonnet 4.6 Thinking 1M", kind: None },
            ProviderModel { id: "claude-sonnet-4.6-1m", name: "Claude Sonnet 4.6 1M", kind: None },
            ProviderModel { id: "claude-sonnet-4.6-thinking", name: "Claude Sonnet 4.6 Thinking", kind: None },
            ProviderModel { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6", kind: None },
            ProviderModel { id: "claude-opus-4.6-thinking", name: "Claude Opus 4.6 Thinking", kind: None },
            ProviderModel { id: "claude-opus-4.6", name: "Claude Opus 4.6", kind: None },
            ProviderModel { id: "claude-opus-4.5-thinking", name: "Claude Opus 4.5 Thinking", kind: None },
            ProviderModel { id: "claude-opus-4.5", name: "Claude Opus 4.5", kind: None },
            ProviderModel { id: "claude-sonnet-4.5-thinking", name: "Claude Sonnet 4.5 Thinking", kind: None },
            ProviderModel { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5", kind: None },
            ProviderModel { id: "claude-haiku-4.5", name: "Claude Haiku 4.5", kind: None },
            ProviderModel { id: "gpt-5.5-xhigh-fast", name: "GPT-5.5 XHigh Fast", kind: None },
            ProviderModel { id: "gpt-5.5-xhigh", name: "GPT-5.5 XHigh", kind: None },
            ProviderModel { id: "gpt-5.5-high-fast", name: "GPT-5.5 High Fast", kind: None },
            ProviderModel { id: "gpt-5.5-high", name: "GPT-5.5 High", kind: None },
            ProviderModel { id: "gpt-5.5-medium-fast", name: "GPT-5.5 Medium Fast", kind: None },
            ProviderModel { id: "gpt-5.5-medium", name: "GPT-5.5 Medium", kind: None },
            ProviderModel { id: "gpt-5.5-low-fast", name: "GPT-5.5 Low Fast", kind: None },
            ProviderModel { id: "gpt-5.5-low", name: "GPT-5.5 Low", kind: None },
            ProviderModel { id: "gpt-5.5-none-fast", name: "GPT-5.5 None Fast", kind: None },
            ProviderModel { id: "gpt-5.5-none", name: "GPT-5.5 None", kind: None },
            ProviderModel { id: "gpt-5.4-xhigh-fast", name: "GPT-5.4 XHigh Fast", kind: None },
            ProviderModel { id: "gpt-5.4-xhigh", name: "GPT-5.4 XHigh", kind: None },
            ProviderModel { id: "gpt-5.4-high-fast", name: "GPT-5.4 High Fast", kind: None },
            ProviderModel { id: "gpt-5.4-high", name: "GPT-5.4 High", kind: None },
            ProviderModel { id: "gpt-5.4-medium-fast", name: "GPT-5.4 Medium Fast", kind: None },
            ProviderModel { id: "gpt-5.4-medium", name: "GPT-5.4 Medium", kind: None },
            ProviderModel { id: "gpt-5.4-low-fast", name: "GPT-5.4 Low Fast", kind: None },
            ProviderModel { id: "gpt-5.4-low", name: "GPT-5.4 Low", kind: None },
            ProviderModel { id: "gpt-5.4-none-fast", name: "GPT-5.4 None Fast", kind: None },
            ProviderModel { id: "gpt-5.4-none", name: "GPT-5.4 None", kind: None },
            ProviderModel { id: "gpt-5.4-mini-xhigh", name: "GPT-5.4 Mini XHigh", kind: None },
            ProviderModel { id: "gpt-5.4-mini-high", name: "GPT-5.4 Mini High", kind: None },
            ProviderModel { id: "gpt-5.4-mini-medium", name: "GPT-5.4 Mini Medium", kind: None },
            ProviderModel { id: "gpt-5.4-mini-low", name: "GPT-5.4 Mini Low", kind: None },
            ProviderModel { id: "gpt-5.3-codex-xhigh-fast", name: "GPT-5.3 Codex XHigh Fast", kind: None },
            ProviderModel { id: "gpt-5.3-codex-xhigh", name: "GPT-5.3 Codex XHigh", kind: None },
            ProviderModel { id: "gpt-5.3-codex-high-fast", name: "GPT-5.3 Codex High Fast", kind: None },
            ProviderModel { id: "gpt-5.3-codex-high", name: "GPT-5.3 Codex High", kind: None },
            ProviderModel { id: "gpt-5.3-codex-medium-fast", name: "GPT-5.3 Codex Medium Fast", kind: None },
            ProviderModel { id: "gpt-5.3-codex-medium", name: "GPT-5.3 Codex Medium", kind: None },
            ProviderModel { id: "gpt-5.3-codex-low-fast", name: "GPT-5.3 Codex Low Fast", kind: None },
            ProviderModel { id: "gpt-5.3-codex-low", name: "GPT-5.3 Codex Low", kind: None },
            ProviderModel { id: "gpt-5.2-xhigh", name: "GPT-5.2 XHigh", kind: None },
            ProviderModel { id: "gpt-5.2-high", name: "GPT-5.2 High", kind: None },
            ProviderModel { id: "gpt-5.2-medium", name: "GPT-5.2 Medium", kind: None },
            ProviderModel { id: "gpt-5.2-low", name: "GPT-5.2 Low", kind: None },
            ProviderModel { id: "gpt-5.2-none", name: "GPT-5.2 None", kind: None },
            ProviderModel { id: "gpt-5", name: "GPT-5", kind: None },
            ProviderModel { id: "gpt-4.1", name: "GPT-4.1", kind: None },
            ProviderModel { id: "gpt-4.1-mini", name: "GPT-4.1 Mini", kind: None },
            ProviderModel { id: "gpt-4.1-nano", name: "GPT-4.1 Nano", kind: None },
            ProviderModel { id: "gpt-4o", name: "GPT-4o", kind: None },
            ProviderModel { id: "gpt-4o-mini", name: "GPT-4o Mini", kind: None },
            ProviderModel { id: "gemini-3.1-pro-high", name: "Gemini 3.1 Pro High", kind: None },
            ProviderModel { id: "gemini-3.1-pro-low", name: "Gemini 3.1 Pro Low", kind: None },
            ProviderModel { id: "gemini-3.0-flash-high", name: "Gemini 3 Flash High", kind: None },
            ProviderModel { id: "gemini-3.0-flash-medium", name: "Gemini 3 Flash Medium", kind: None },
            ProviderModel { id: "gemini-3.0-flash-low", name: "Gemini 3 Flash Low", kind: None },
            ProviderModel { id: "gemini-3.0-flash-minimal", name: "Gemini 3 Flash Minimal", kind: None },
            ProviderModel { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", kind: None },
            ProviderModel { id: "deepseek-v4", name: "DeepSeek V4", kind: None },
            ProviderModel { id: "kimi-k2.6", name: "Kimi K2.6", kind: None },
            ProviderModel { id: "kimi-k2.5", name: "Kimi K2.5", kind: None },
            ProviderModel { id: "glm-5.1", name: "GLM-5.1", kind: None },
        ],
        service_kinds: &[],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "xai",
        priority: 280,
        alias: "xai",
        ui_alias: None,
        display: ProviderDisplay { name: "xAI (Grok)", icon: Some("auto_awesome"), color: Some("#1DA1F2"), text_icon: Some("XA"), website: Some("https://x.ai"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://api.x.ai/v1/chat/completions"),
            ..DEFAULT_TRANSPORT
        },
        models: &[
            ProviderModel { id: "grok-4.6", name: "Grok 4.6", kind: None },
            ProviderModel { id: "grok-4.5", name: "Grok 4.5", kind: None },
            ProviderModel { id: "grok-4", name: "Grok 4", kind: None },
            ProviderModel { id: "grok-4-fast-reasoning", name: "Grok 4 Fast Reasoning", kind: None },
            ProviderModel { id: "grok-code-fast-1", name: "Grok Code Fast", kind: None },
            ProviderModel { id: "grok-3", name: "Grok 3", kind: None },
            ProviderModel { id: "grok-2-image-1212", name: "Grok 2 Image", kind: Some("image") },
            ProviderModel { id: "grok-imagine-video", name: "Grok Imagine Video", kind: Some("video") },
        ],
        service_kinds: &["llm", "imageToText", "webSearch", "image", "video"],
        hidden: false,
    },
    ProviderRegistryEntry {
        id: "zed",
        priority: 10,
        alias: "zd",
        ui_alias: Some("zd"),
        display: ProviderDisplay { name: "Zed", icon: Some("code"), color: Some("#A855F7"), text_icon: None, website: Some("https://zed.dev"), notice: None },
        category: ProviderCategory::Oauth,
        transport: ProviderTransport {
            base_url: Some("https://cloud.zed.dev/completions"),
            format: Some("openai"),
            force_stream: Some(true),
            headers: &[("content-type", "application/json")],
            auth: Some(ProviderAuth { combined: true, header: "Authorization", scheme: "" }),
            ..DEFAULT_TRANSPORT
        },
        models: &[],
        service_kinds: &[],
        hidden: true,
    },
];
